# This file was auto-generated by Fern from our API Definition.

import typing

CreateSdkKeyRequestScopesItem = typing.Union[
    typing.Literal["traces:write", "events:read", "events:write", "users:write", "signals:write", "agents:write"],
    typing.Any,
]
