# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class CreateBacktestJobRequestCasesItem(UniversalBaseModel):
    """
    One explicit case accepted by `POST /v1/backtests/jobs` for non-Dataset recipes. Dataset-backed requests use these entries only as a case-id selection; the server always loads the instruction and expected outcome from the pinned Dataset Version.
    """

    case_cluster: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="caseCluster"), pydantic.Field(alias="caseCluster")
    ] = None
    case_id: typing_extensions.Annotated[str, FieldMetadata(alias="caseId"), pydantic.Field(alias="caseId")]
    expected_outcome: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="expectedOutcome"), pydantic.Field(alias="expectedOutcome")
    ] = None
    instruction: typing.Optional[str] = pydantic.Field(default=None)
    """
    Required for composed recipes. Dataset-backed requests may omit it because the server loads canonical content from the pinned Version.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
