# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_backtest_job_request_recipe_agents_item import CreateBacktestJobRequestRecipeAgentsItem
from .create_backtest_job_request_recipe_data import CreateBacktestJobRequestRecipeData
from .create_backtest_job_request_recipe_environment import CreateBacktestJobRequestRecipeEnvironment
from .create_backtest_job_request_recipe_graders_item import CreateBacktestJobRequestRecipeGradersItem
from .create_backtest_job_request_recipe_mode import CreateBacktestJobRequestRecipeMode


class CreateBacktestJobRequestRecipe(UniversalBaseModel):
    agents: typing.List[CreateBacktestJobRequestRecipeAgentsItem] = pydantic.Field()
    """
    1..N agents under test. The first is treated as the comparison baseline by `BacktestResults`.
    """

    data: CreateBacktestJobRequestRecipeData
    environment: typing.Optional[CreateBacktestJobRequestRecipeEnvironment] = pydantic.Field(default=None)
    """
    Optional environment the run targets. Pipeline step 03 sets this; consumers without an environment fall back to the default ephemeral sandbox.
    """

    graders: typing.List[CreateBacktestJobRequestRecipeGradersItem]
    mode: CreateBacktestJobRequestRecipeMode
    name: str = pydantic.Field()
    """
    Free-text run name shown in the recipe header + top nav.
    """

    seed: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional pinned trace seed; used by the Replay preset to reproduce a single trace as the focal point of the run.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
