# This file was auto-generated by Fern from our API Definition.

import typing

CreateBacktestJobRequestRecipeGradersItemSource = typing.Union[
    typing.Literal["proposed", "library", "custom", "dataset"], typing.Any
]
