# This file was auto-generated by Fern from our API Definition.

import typing

CreateBacktestJobRequestRecipeMode = typing.Union[
    typing.Literal["replay", "compare", "regression", "suite"], typing.Any
]
