# This file was auto-generated by Fern from our API Definition.

import typing

CreateBacktestJobRequestRecipeDataScenariosItemBucket = typing.Union[
    typing.Literal["captured", "adjacent", "emerging", "edge"], typing.Any
]
