# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .create_backtest_job_request_recipe_data_sources_item_filters import (
    CreateBacktestJobRequestRecipeDataSourcesItemFilters,
)
from .create_backtest_job_request_recipe_data_sources_item_kind import CreateBacktestJobRequestRecipeDataSourcesItemKind


class CreateBacktestJobRequestRecipeDataSourcesItem(UniversalBaseModel):
    count: int
    filters: typing.Optional[CreateBacktestJobRequestRecipeDataSourcesItemFilters] = None
    id: str
    kind: CreateBacktestJobRequestRecipeDataSourcesItemKind
    label: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
