# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .create_backtest_job_request_recipe_data_kind import CreateBacktestJobRequestRecipeDataKind
from .create_backtest_job_request_recipe_data_scenarios_item import CreateBacktestJobRequestRecipeDataScenariosItem
from .create_backtest_job_request_recipe_data_sources_item import CreateBacktestJobRequestRecipeDataSourcesItem


class CreateBacktestJobRequestRecipeData(UniversalBaseModel):
    dataset: typing.Optional[str] = pydantic.Field(default=None)
    """
    Populated only when `kind == "dataset"`.
    """

    dataset_label: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="datasetLabel"), pydantic.Field(alias="datasetLabel")
    ] = None
    kind: CreateBacktestJobRequestRecipeDataKind
    saved_as: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="savedAs"),
        pydantic.Field(
            alias="savedAs",
            description="Optional name the user wants to save this composed dataset as. `null` (vs absent) tells the UI the user opted out of saving.",
        ),
    ] = None
    """
    Optional name the user wants to save this composed dataset as. `null` (vs absent) tells the UI the user opted out of saving.
    """

    scenarios: typing.List[CreateBacktestJobRequestRecipeDataScenariosItem]
    sources: typing.List[CreateBacktestJobRequestRecipeDataSourcesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
