# This file was auto-generated by Fern from our API Definition.

import typing

CreateBacktestJobRequestRecipeDataScenariosItemKind = typing.Union[
    typing.Literal["adversarial", "nonEnglish", "toolFailure", "longTurn"], typing.Any
]
