# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.created_sdk_key import CreatedSdkKey
from ..types.sdk_key_list_response import SdkKeyListResponse
from .raw_client import AsyncRawCredentialsClient, RawCredentialsClient
from .types.create_sdk_key_request_scopes_item import CreateSdkKeyRequestScopesItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CredentialsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCredentialsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCredentialsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCredentialsClient
        """
        return self._raw_client

    def list_sdk_keys(self, *, request_options: typing.Optional[RequestOptions] = None) -> SdkKeyListResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkKeyListResponse
            Active SDK keys

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.credentials.list_sdk_keys()
        """
        _response = self._raw_client.list_sdk_keys(request_options=request_options)
        return _response.data

    def create_sdk_key(
        self,
        *,
        name: str,
        scopes: typing.Sequence[CreateSdkKeyRequestScopesItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatedSdkKey:
        """
        The bearer secret is returned once and is not stored in plaintext.

        Parameters
        ----------
        name : str

        scopes : typing.Sequence[CreateSdkKeyRequestScopesItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatedSdkKey
            SDK key and one-time bearer secret

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.credentials.create_sdk_key(
            name="name",
            scopes=["traces:write"],
        )
        """
        _response = self._raw_client.create_sdk_key(name=name, scopes=scopes, request_options=request_options)
        return _response.data

    def revoke_sdk_key(self, key_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        key_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.credentials.revoke_sdk_key(
            key_id="key_id",
        )
        """
        _response = self._raw_client.revoke_sdk_key(key_id, request_options=request_options)
        return _response.data


class AsyncCredentialsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCredentialsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCredentialsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCredentialsClient
        """
        return self._raw_client

    async def list_sdk_keys(self, *, request_options: typing.Optional[RequestOptions] = None) -> SdkKeyListResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SdkKeyListResponse
            Active SDK keys

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.credentials.list_sdk_keys()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sdk_keys(request_options=request_options)
        return _response.data

    async def create_sdk_key(
        self,
        *,
        name: str,
        scopes: typing.Sequence[CreateSdkKeyRequestScopesItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatedSdkKey:
        """
        The bearer secret is returned once and is not stored in plaintext.

        Parameters
        ----------
        name : str

        scopes : typing.Sequence[CreateSdkKeyRequestScopesItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatedSdkKey
            SDK key and one-time bearer secret

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.credentials.create_sdk_key(
                name="name",
                scopes=["traces:write"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_sdk_key(name=name, scopes=scopes, request_options=request_options)
        return _response.data

    async def revoke_sdk_key(self, key_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        key_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.credentials.revoke_sdk_key(
                key_id="key_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_sdk_key(key_id, request_options=request_options)
        return _response.data
