# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.entity_list_response import EntityListResponse
from ..types.entity_type_list_response import EntityTypeListResponse
from ..types.source_list_response import SourceListResponse
from ..types.source_schema import SourceSchema
from .raw_client import AsyncRawDiscoverClient, RawDiscoverClient


class DiscoverClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawDiscoverClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawDiscoverClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawDiscoverClient
        """
        return self._raw_client

    def list_sources(self, *, request_options: typing.Optional[RequestOptions] = None) -> SourceListResponse:
        """
        Requires scope events:read or events:write. Returns the complete source metadata set without pagination.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceListResponse
            Sources

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.discover.list_sources()
        """
        _response = self._raw_client.list_sources(request_options=request_options)
        return _response.data

    def list_entity_types(self, *, request_options: typing.Optional[RequestOptions] = None) -> EntityTypeListResponse:
        """
        Requires scope events:read or events:write. Returns the complete entity-type metadata set without pagination.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityTypeListResponse
            Entity types

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.discover.list_entity_types()
        """
        _response = self._raw_client.list_entity_types(request_options=request_options)
        return _response.data

    def list_entities(
        self,
        entity_type: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityListResponse:
        """
        Requires scope events:read or events:write. Entities are ordered by event count and entity ID. The limit is capped at 200; pass `next_cursor` as `cursor`.

        Parameters
        ----------
        entity_type : str

        limit : typing.Optional[int]
            Page size. Values above 200 are clamped to 200.

        cursor : typing.Optional[str]
            Opaque position returned as `next_cursor` by the preceding page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityListResponse
            Entities

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.discover.list_entities(
            entity_type="entity_type",
        )
        """
        _response = self._raw_client.list_entities(
            entity_type, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    def get_event_schema(
        self, source: str, event_type: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceSchema:
        """
        Requires scope events:read or events:write.

        Parameters
        ----------
        source : str

        event_type : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceSchema
            Observed schema

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.discover.get_event_schema(
            source="source",
            event_type="event_type",
        )
        """
        _response = self._raw_client.get_event_schema(source, event_type, request_options=request_options)
        return _response.data


class AsyncDiscoverClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawDiscoverClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawDiscoverClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawDiscoverClient
        """
        return self._raw_client

    async def list_sources(self, *, request_options: typing.Optional[RequestOptions] = None) -> SourceListResponse:
        """
        Requires scope events:read or events:write. Returns the complete source metadata set without pagination.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceListResponse
            Sources

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.discover.list_sources()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_sources(request_options=request_options)
        return _response.data

    async def list_entity_types(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EntityTypeListResponse:
        """
        Requires scope events:read or events:write. Returns the complete entity-type metadata set without pagination.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityTypeListResponse
            Entity types

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.discover.list_entity_types()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_entity_types(request_options=request_options)
        return _response.data

    async def list_entities(
        self,
        entity_type: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EntityListResponse:
        """
        Requires scope events:read or events:write. Entities are ordered by event count and entity ID. The limit is capped at 200; pass `next_cursor` as `cursor`.

        Parameters
        ----------
        entity_type : str

        limit : typing.Optional[int]
            Page size. Values above 200 are clamped to 200.

        cursor : typing.Optional[str]
            Opaque position returned as `next_cursor` by the preceding page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EntityListResponse
            Entities

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.discover.list_entities(
                entity_type="entity_type",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_entities(
            entity_type, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def get_event_schema(
        self, source: str, event_type: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SourceSchema:
        """
        Requires scope events:read or events:write.

        Parameters
        ----------
        source : str

        event_type : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SourceSchema
            Observed schema

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.discover.get_event_schema(
                source="source",
                event_type="event_type",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_event_schema(source, event_type, request_options=request_options)
        return _response.data
