# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.event_list_response import EventListResponse
from .raw_client import AsyncRawSearchClient, RawSearchClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SearchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSearchClient
        """
        return self._raw_client

    def events(
        self,
        *,
        query: str,
        source: typing.Optional[str] = OMIT,
        entity_type: typing.Optional[str] = OMIT,
        entity_id: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventListResponse:
        """
        Requires scope events:read or events:write. The page size is capped at 200 and a cursor can advance through at most 1,000 relevance-ranked results. Each request consumes 5 rate-limit units.

        Parameters
        ----------
        query : str

        source : typing.Optional[str]

        entity_type : typing.Optional[str]

        entity_id : typing.Optional[str]

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque position returned by the preceding search page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventListResponse
            Search results

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.search.events(
            query="query",
        )
        """
        _response = self._raw_client.events(
            query=query,
            source=source,
            entity_type=entity_type,
            entity_id=entity_id,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data


class AsyncSearchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSearchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSearchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSearchClient
        """
        return self._raw_client

    async def events(
        self,
        *,
        query: str,
        source: typing.Optional[str] = OMIT,
        entity_type: typing.Optional[str] = OMIT,
        entity_id: typing.Optional[str] = OMIT,
        limit: typing.Optional[int] = OMIT,
        cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventListResponse:
        """
        Requires scope events:read or events:write. The page size is capped at 200 and a cursor can advance through at most 1,000 relevance-ranked results. Each request consumes 5 rate-limit units.

        Parameters
        ----------
        query : str

        source : typing.Optional[str]

        entity_type : typing.Optional[str]

        entity_id : typing.Optional[str]

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque position returned by the preceding search page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventListResponse
            Search results

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.search.events(
                query="query",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.events(
            query=query,
            source=source,
            entity_type=entity_type,
            entity_id=entity_id,
            limit=limit,
            cursor=cursor,
            request_options=request_options,
        )
        return _response.data
