# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        AcceptedResponse,
        CreateLinkResponse,
        EntityInfo,
        EntityListResponse,
        EntityRef,
        EntityTypeInfo,
        EntityTypeListResponse,
        ErrorResponse,
        ErrorResponseCode,
        Event,
        EventListResponse,
        EventPage,
        EventResult,
        IngestRequest,
        IngestResponse,
        LinkEntityResponse,
        MediaAttachment,
        PendingEntityRef,
        SignalRequest,
        SourceInfo,
        SourceListResponse,
        SourceSchema,
        SpanRequest,
        StatusResponse,
        TraceRequest,
    )
    from .errors import (
        BadRequestError,
        ConflictError,
        ContentTooLargeError,
        GatewayTimeoutError,
        InternalServerError,
        NotFoundError,
        ServiceUnavailableError,
        TooManyRequestsError,
        UnauthorizedError,
        UnprocessableEntityError,
        UnsupportedMediaTypeError,
    )
    from . import discover, events, links, sdk, search, timeline
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .client import AsyncChronicle, Chronicle
    from .environment import ChronicleEnvironment
    from .links import GraphRequestDirection
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "AcceptedResponse": ".types",
    "AsyncChronicle": ".client",
    "BadRequestError": ".errors",
    "Chronicle": ".client",
    "ChronicleEnvironment": ".environment",
    "ConflictError": ".errors",
    "ContentTooLargeError": ".errors",
    "CreateLinkResponse": ".types",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "EntityInfo": ".types",
    "EntityListResponse": ".types",
    "EntityRef": ".types",
    "EntityTypeInfo": ".types",
    "EntityTypeListResponse": ".types",
    "ErrorResponse": ".types",
    "ErrorResponseCode": ".types",
    "Event": ".types",
    "EventListResponse": ".types",
    "EventPage": ".types",
    "EventResult": ".types",
    "GatewayTimeoutError": ".errors",
    "GraphRequestDirection": ".links",
    "IngestRequest": ".types",
    "IngestResponse": ".types",
    "InternalServerError": ".errors",
    "LinkEntityResponse": ".types",
    "MediaAttachment": ".types",
    "NotFoundError": ".errors",
    "PendingEntityRef": ".types",
    "ServiceUnavailableError": ".errors",
    "SignalRequest": ".types",
    "SourceInfo": ".types",
    "SourceListResponse": ".types",
    "SourceSchema": ".types",
    "SpanRequest": ".types",
    "StatusResponse": ".types",
    "TooManyRequestsError": ".errors",
    "TraceRequest": ".types",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "UnsupportedMediaTypeError": ".errors",
    "__version__": ".version",
    "discover": ".discover",
    "events": ".events",
    "links": ".links",
    "sdk": ".sdk",
    "search": ".search",
    "timeline": ".timeline",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AcceptedResponse",
    "AsyncChronicle",
    "BadRequestError",
    "Chronicle",
    "ChronicleEnvironment",
    "ConflictError",
    "ContentTooLargeError",
    "CreateLinkResponse",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "EntityInfo",
    "EntityListResponse",
    "EntityRef",
    "EntityTypeInfo",
    "EntityTypeListResponse",
    "ErrorResponse",
    "ErrorResponseCode",
    "Event",
    "EventListResponse",
    "EventPage",
    "EventResult",
    "GatewayTimeoutError",
    "GraphRequestDirection",
    "IngestRequest",
    "IngestResponse",
    "InternalServerError",
    "LinkEntityResponse",
    "MediaAttachment",
    "NotFoundError",
    "PendingEntityRef",
    "ServiceUnavailableError",
    "SignalRequest",
    "SourceInfo",
    "SourceListResponse",
    "SourceSchema",
    "SpanRequest",
    "StatusResponse",
    "TooManyRequestsError",
    "TraceRequest",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "UnsupportedMediaTypeError",
    "__version__",
    "discover",
    "events",
    "links",
    "sdk",
    "search",
    "timeline",
]
