# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.agent_chat_session import AgentChatSession
from ..types.agent_snapshot import AgentSnapshot
from ..types.agent_summary import AgentSummary
from ..types.agent_version_summary import AgentVersionSummary
from ..types.create_agent_chat_session_response import CreateAgentChatSessionResponse
from ..types.hash_index_entry import HashIndexEntry
from ..types.send_agent_chat_message_response import SendAgentChatMessageResponse
from .raw_client import AsyncRawAgentsClient, RawAgentsClient
from .types.record_agent_runs_request_runs_item import RecordAgentRunsRequestRunsItem
from .types.record_agent_runs_response import RecordAgentRunsResponse
from .types.register_agent_artifact_request_artifact import RegisterAgentArtifactRequestArtifact
from .types.register_agent_artifact_request_metadata import RegisterAgentArtifactRequestMetadata
from .types.register_agent_artifact_request_status import RegisterAgentArtifactRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentsClient
        """
        return self._raw_client

    def list_agents(self, *, request_options: typing.Optional[RequestOptions] = None) -> typing.List[AgentSummary]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[AgentSummary]
            Registered agents

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.list_agents()
        """
        _response = self._raw_client.list_agents(request_options=request_options)
        return _response.data

    def search_agent_hash_index(
        self,
        *,
        q: typing.Optional[str] = None,
        domains: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[HashIndexEntry]:
        """
        Parameters
        ----------
        q : typing.Optional[str]

        domains : typing.Optional[str]
            Comma-separated hash domains.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[HashIndexEntry]
            Matching hash index entries

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.search_agent_hash_index()
        """
        _response = self._raw_client.search_agent_hash_index(q=q, domains=domains, request_options=request_options)
        return _response.data

    def subscribe_to_agent_changes(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[typing.Dict[str, typing.Any]]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[typing.Dict[str, typing.Any]]
            Server-Sent Events carrying registry snapshots

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        response = client.agents.subscribe_to_agent_changes()
        for chunk in response:
            yield chunk
        """
        with self._raw_client.subscribe_to_agent_changes(request_options=request_options) as r:
            yield from r.data

    def update_agent(
        self,
        name: str,
        *,
        description: typing.Optional[str] = OMIT,
        environment: typing.Optional[str] = OMIT,
        owner: typing.Optional[str] = OMIT,
        purpose: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSummary:
        """
        Parameters
        ----------
        name : str

        description : typing.Optional[str]

        environment : typing.Optional[str]

        owner : typing.Optional[str]

        purpose : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSummary
            Updated agent

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.update_agent(
            name="name",
        )
        """
        _response = self._raw_client.update_agent(
            name,
            description=description,
            environment=environment,
            owner=owner,
            purpose=purpose,
            request_options=request_options,
        )
        return _response.data

    def get_agent_snapshot(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[AgentSnapshot]:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[AgentSnapshot]
            Latest snapshot, or null when the agent has no version

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.get_agent_snapshot(
            name="name",
        )
        """
        _response = self._raw_client.get_agent_snapshot(name, request_options=request_options)
        return _response.data

    def pin_latest_agent_version(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentSummary:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSummary
            Agent with its latest version pinned

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.pin_latest_agent_version(
            name="name",
        )
        """
        _response = self._raw_client.pin_latest_agent_version(name, request_options=request_options)
        return _response.data

    def create_agent_chat_session(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAgentChatSessionResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentChatSessionResponse
            Chat session created

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.create_agent_chat_session(
            name="name",
        )
        """
        _response = self._raw_client.create_agent_chat_session(name, request_options=request_options)
        return _response.data

    def get_agent_chat_session(
        self, name: str, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentChatSession:
        """
        Parameters
        ----------
        name : str

        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentChatSession
            Chat session

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.get_agent_chat_session(
            name="name",
            session_id="session_id",
        )
        """
        _response = self._raw_client.get_agent_chat_session(name, session_id, request_options=request_options)
        return _response.data

    def send_agent_chat_message(
        self, name: str, session_id: str, *, text: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SendAgentChatMessageResponse:
        """
        Parameters
        ----------
        name : str

        session_id : str

        text : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SendAgentChatMessageResponse
            Updated chat session

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.send_agent_chat_message(
            name="name",
            session_id="session_id",
            text="text",
        )
        """
        _response = self._raw_client.send_agent_chat_message(
            name, session_id, text=text, request_options=request_options
        )
        return _response.data

    def register_agent_artifact(
        self,
        *,
        artifact: RegisterAgentArtifactRequestArtifact,
        metadata: typing.Optional[RegisterAgentArtifactRequestMetadata] = OMIT,
        status: typing.Optional[RegisterAgentArtifactRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentVersionSummary:
        """
        Requires scope agents:write.

        Parameters
        ----------
        artifact : RegisterAgentArtifactRequestArtifact

        metadata : typing.Optional[RegisterAgentArtifactRequestMetadata]
            Mutable, human-authored metadata attached to a logical Agent identity. Artifact configuration remains immutable inside `AgentRegistryVersionRecord`.

        status : typing.Optional[RegisterAgentArtifactRequestStatus]
            Defaults to `current`. Registering a new current version atomically demotes the previous current version to stable.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentVersionSummary
            Registered agent version

        Examples
        --------
        import datetime

        from chroniclelabs import Chronicle
        from chroniclelabs.agents import (
            RegisterAgentArtifactRequestArtifact,
            RegisterAgentArtifactRequestArtifactModel,
            RegisterAgentArtifactRequestArtifactProvenance,
            RegisterAgentArtifactRequestArtifactToolsItem,
        )

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.register_agent_artifact(
            artifact=RegisterAgentArtifactRequestArtifact(
                artifact_id="artifactId",
                config_hash="configHash",
                framework="vercel-ai-sdk",
                model=RegisterAgentArtifactRequestArtifactModel(
                    label="label",
                ),
                name="name",
                provenance=RegisterAgentArtifactRequestArtifactProvenance(
                    created_at=datetime.datetime.fromisoformat(
                        "2024-01-15 09:30:00+00:00",
                    ),
                ),
                schema_version="schemaVersion",
                tools=[
                    RegisterAgentArtifactRequestArtifactToolsItem(
                        name="name",
                    )
                ],
                version="version",
            ),
        )
        """
        _response = self._raw_client.register_agent_artifact(
            artifact=artifact, metadata=metadata, status=status, request_options=request_options
        )
        return _response.data

    def record_agent_runs(
        self,
        *,
        runs: typing.Sequence[RecordAgentRunsRequestRunsItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecordAgentRunsResponse:
        """
        Requires scope agents:write.

        Parameters
        ----------
        runs : typing.Sequence[RecordAgentRunsRequestRunsItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordAgentRunsResponse
            Runs accepted

        Examples
        --------
        import datetime

        from chroniclelabs import Chronicle
        from chroniclelabs.agents import (
            RecordAgentRunsRequestRunsItem,
            RecordAgentRunsRequestRunsItemToolCallsItem,
        )

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.agents.record_agent_runs(
            runs=[
                RecordAgentRunsRequestRunsItem(
                    artifact_id="artifactId",
                    config_hash="configHash",
                    operation="generate",
                    run_id="runId",
                    schema_version="schemaVersion",
                    started_at=datetime.datetime.fromisoformat(
                        "2024-01-15 09:30:00+00:00",
                    ),
                    status="started",
                    tool_calls=[
                        RecordAgentRunsRequestRunsItemToolCallsItem(
                            call_id="callId",
                            started_at=datetime.datetime.fromisoformat(
                                "2024-01-15 09:30:00+00:00",
                            ),
                            status="started",
                            tool_name="toolName",
                        )
                    ],
                )
            ],
        )
        """
        _response = self._raw_client.record_agent_runs(runs=runs, request_options=request_options)
        return _response.data


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentsClient
        """
        return self._raw_client

    async def list_agents(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[AgentSummary]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[AgentSummary]
            Registered agents

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.list_agents()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agents(request_options=request_options)
        return _response.data

    async def search_agent_hash_index(
        self,
        *,
        q: typing.Optional[str] = None,
        domains: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.List[HashIndexEntry]:
        """
        Parameters
        ----------
        q : typing.Optional[str]

        domains : typing.Optional[str]
            Comma-separated hash domains.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[HashIndexEntry]
            Matching hash index entries

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.search_agent_hash_index()


        asyncio.run(main())
        """
        _response = await self._raw_client.search_agent_hash_index(
            q=q, domains=domains, request_options=request_options
        )
        return _response.data

    async def subscribe_to_agent_changes(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[typing.Dict[str, typing.Any]]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[typing.Dict[str, typing.Any]]
            Server-Sent Events carrying registry snapshots

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = client.agents.subscribe_to_agent_changes()
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.subscribe_to_agent_changes(request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def update_agent(
        self,
        name: str,
        *,
        description: typing.Optional[str] = OMIT,
        environment: typing.Optional[str] = OMIT,
        owner: typing.Optional[str] = OMIT,
        purpose: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentSummary:
        """
        Parameters
        ----------
        name : str

        description : typing.Optional[str]

        environment : typing.Optional[str]

        owner : typing.Optional[str]

        purpose : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSummary
            Updated agent

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.update_agent(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_agent(
            name,
            description=description,
            environment=environment,
            owner=owner,
            purpose=purpose,
            request_options=request_options,
        )
        return _response.data

    async def get_agent_snapshot(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[AgentSnapshot]:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[AgentSnapshot]
            Latest snapshot, or null when the agent has no version

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.get_agent_snapshot(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent_snapshot(name, request_options=request_options)
        return _response.data

    async def pin_latest_agent_version(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentSummary:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentSummary
            Agent with its latest version pinned

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.pin_latest_agent_version(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.pin_latest_agent_version(name, request_options=request_options)
        return _response.data

    async def create_agent_chat_session(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CreateAgentChatSessionResponse:
        """
        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentChatSessionResponse
            Chat session created

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.create_agent_chat_session(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_agent_chat_session(name, request_options=request_options)
        return _response.data

    async def get_agent_chat_session(
        self, name: str, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentChatSession:
        """
        Parameters
        ----------
        name : str

        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentChatSession
            Chat session

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.get_agent_chat_session(
                name="name",
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent_chat_session(name, session_id, request_options=request_options)
        return _response.data

    async def send_agent_chat_message(
        self, name: str, session_id: str, *, text: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SendAgentChatMessageResponse:
        """
        Parameters
        ----------
        name : str

        session_id : str

        text : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SendAgentChatMessageResponse
            Updated chat session

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.send_agent_chat_message(
                name="name",
                session_id="session_id",
                text="text",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.send_agent_chat_message(
            name, session_id, text=text, request_options=request_options
        )
        return _response.data

    async def register_agent_artifact(
        self,
        *,
        artifact: RegisterAgentArtifactRequestArtifact,
        metadata: typing.Optional[RegisterAgentArtifactRequestMetadata] = OMIT,
        status: typing.Optional[RegisterAgentArtifactRequestStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentVersionSummary:
        """
        Requires scope agents:write.

        Parameters
        ----------
        artifact : RegisterAgentArtifactRequestArtifact

        metadata : typing.Optional[RegisterAgentArtifactRequestMetadata]
            Mutable, human-authored metadata attached to a logical Agent identity. Artifact configuration remains immutable inside `AgentRegistryVersionRecord`.

        status : typing.Optional[RegisterAgentArtifactRequestStatus]
            Defaults to `current`. Registering a new current version atomically demotes the previous current version to stable.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentVersionSummary
            Registered agent version

        Examples
        --------
        import asyncio
        import datetime

        from chroniclelabs import AsyncChronicle
        from chroniclelabs.agents import (
            RegisterAgentArtifactRequestArtifact,
            RegisterAgentArtifactRequestArtifactModel,
            RegisterAgentArtifactRequestArtifactProvenance,
            RegisterAgentArtifactRequestArtifactToolsItem,
        )

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.register_agent_artifact(
                artifact=RegisterAgentArtifactRequestArtifact(
                    artifact_id="artifactId",
                    config_hash="configHash",
                    framework="vercel-ai-sdk",
                    model=RegisterAgentArtifactRequestArtifactModel(
                        label="label",
                    ),
                    name="name",
                    provenance=RegisterAgentArtifactRequestArtifactProvenance(
                        created_at=datetime.datetime.fromisoformat(
                            "2024-01-15 09:30:00+00:00",
                        ),
                    ),
                    schema_version="schemaVersion",
                    tools=[
                        RegisterAgentArtifactRequestArtifactToolsItem(
                            name="name",
                        )
                    ],
                    version="version",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.register_agent_artifact(
            artifact=artifact, metadata=metadata, status=status, request_options=request_options
        )
        return _response.data

    async def record_agent_runs(
        self,
        *,
        runs: typing.Sequence[RecordAgentRunsRequestRunsItem],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RecordAgentRunsResponse:
        """
        Requires scope agents:write.

        Parameters
        ----------
        runs : typing.Sequence[RecordAgentRunsRequestRunsItem]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RecordAgentRunsResponse
            Runs accepted

        Examples
        --------
        import asyncio
        import datetime

        from chroniclelabs import AsyncChronicle
        from chroniclelabs.agents import (
            RecordAgentRunsRequestRunsItem,
            RecordAgentRunsRequestRunsItemToolCallsItem,
        )

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.record_agent_runs(
                runs=[
                    RecordAgentRunsRequestRunsItem(
                        artifact_id="artifactId",
                        config_hash="configHash",
                        operation="generate",
                        run_id="runId",
                        schema_version="schemaVersion",
                        started_at=datetime.datetime.fromisoformat(
                            "2024-01-15 09:30:00+00:00",
                        ),
                        status="started",
                        tool_calls=[
                            RecordAgentRunsRequestRunsItemToolCallsItem(
                                call_id="callId",
                                started_at=datetime.datetime.fromisoformat(
                                    "2024-01-15 09:30:00+00:00",
                                ),
                                status="started",
                                tool_name="toolName",
                            )
                        ],
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.record_agent_runs(runs=runs, request_options=request_options)
        return _response.data
