# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.backtest_job_detail_response import BacktestJobDetailResponse
from ..types.backtest_trial_detail_response import BacktestTrialDetailResponse
from ..types.backtests_availability import BacktestsAvailability
from ..types.cancel_backtest_job_response import CancelBacktestJobResponse
from ..types.create_backtest_job_response import CreateBacktestJobResponse
from ..types.list_backtest_job_trials_response import ListBacktestJobTrialsResponse
from ..types.list_backtest_jobs_response import ListBacktestJobsResponse
from ..types.trial_event import TrialEvent
from .raw_client import AsyncRawBacktestsClient, RawBacktestsClient
from .types.create_backtest_job_request_cases_item import CreateBacktestJobRequestCasesItem
from .types.create_backtest_job_request_recipe import CreateBacktestJobRequestRecipe

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class BacktestsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBacktestsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBacktestsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBacktestsClient
        """
        return self._raw_client

    def get_backtests_availability(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BacktestsAvailability:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BacktestsAvailability
            Backtest launch options

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.backtests.get_backtests_availability()
        """
        _response = self._raw_client.get_backtests_availability(request_options=request_options)
        return _response.data

    def list_backtest_jobs(
        self,
        *,
        mode: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBacktestJobsResponse:
        """
        Parameters
        ----------
        mode : typing.Optional[str]

        status : typing.Optional[str]

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque position returned as `next_cursor` by the preceding page.

        offset : typing.Optional[int]
            Deprecated compatibility input. Pass the opaque `cursor` instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBacktestJobsResponse
            Backtest jobs

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.backtests.list_backtest_jobs()
        """
        _response = self._raw_client.list_backtest_jobs(
            mode=mode, status=status, limit=limit, cursor=cursor, offset=offset, request_options=request_options
        )
        return _response.data

    def create_backtest_job(
        self,
        *,
        name: str,
        recipe: CreateBacktestJobRequestRecipe,
        idempotency_key: typing.Optional[str] = None,
        cases: typing.Optional[typing.Sequence[CreateBacktestJobRequestCasesItem]] = OMIT,
        evaluator_profile_id: typing.Optional[str] = OMIT,
        n_concurrent: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateBacktestJobResponse:
        """
        Returns 202 after the durable job and its trials have been admitted.

        Parameters
        ----------
        name : str

        recipe : CreateBacktestJobRequestRecipe

        idempotency_key : typing.Optional[str]
            Optional caller-generated key for safely retrying a mutation after an ambiguous network failure. Keys are scoped to the authenticated tenant and operation. Reusing a key with the same payload returns the original successful result; reusing it with a different payload returns 409.

        cases : typing.Optional[typing.Sequence[CreateBacktestJobRequestCasesItem]]

        evaluator_profile_id : typing.Optional[str]

        n_concurrent : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateBacktestJobResponse
            Backtest job accepted

        Examples
        --------
        from chroniclelabs import Chronicle
        from chroniclelabs.backtests import (
            CreateBacktestJobRequestRecipe,
            CreateBacktestJobRequestRecipeAgentsItem,
            CreateBacktestJobRequestRecipeData,
            CreateBacktestJobRequestRecipeDataScenariosItem,
            CreateBacktestJobRequestRecipeDataSourcesItem,
            CreateBacktestJobRequestRecipeGradersItem,
        )

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.backtests.create_backtest_job(
            name="name",
            recipe=CreateBacktestJobRequestRecipe(
                agents=[
                    CreateBacktestJobRequestRecipeAgentsItem(
                        hue="hue",
                        id="id",
                        label="label",
                        notes="notes",
                    )
                ],
                data=CreateBacktestJobRequestRecipeData(
                    kind="composed",
                    scenarios=[
                        CreateBacktestJobRequestRecipeDataScenariosItem(
                            count=1,
                            id="id",
                            kind="adversarial",
                            label="label",
                        )
                    ],
                    sources=[
                        CreateBacktestJobRequestRecipeDataSourcesItem(
                            count=1,
                            id="id",
                            kind="prod",
                            label="label",
                        )
                    ],
                ),
                graders=[
                    CreateBacktestJobRequestRecipeGradersItem(
                        id="id",
                        kind="rubric",
                        label="label",
                        source="proposed",
                        weight="low",
                    )
                ],
                mode="replay",
                name="name",
            ),
        )
        """
        _response = self._raw_client.create_backtest_job(
            name=name,
            recipe=recipe,
            idempotency_key=idempotency_key,
            cases=cases,
            evaluator_profile_id=evaluator_profile_id,
            n_concurrent=n_concurrent,
            request_options=request_options,
        )
        return _response.data

    def get_backtest_job(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BacktestJobDetailResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BacktestJobDetailResponse
            Backtest job

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.backtests.get_backtest_job(
            job_id="job_id",
        )
        """
        _response = self._raw_client.get_backtest_job(job_id, request_options=request_options)
        return _response.data

    def list_backtest_job_trials(
        self,
        job_id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBacktestJobTrialsResponse:
        """
        Parameters
        ----------
        job_id : str

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque position returned as `next_cursor` by the preceding page.

        offset : typing.Optional[int]
            Deprecated compatibility input. Pass the opaque `cursor` instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBacktestJobTrialsResponse
            Backtest trials and rewards

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.backtests.list_backtest_job_trials(
            job_id="job_id",
        )
        """
        _response = self._raw_client.list_backtest_job_trials(
            job_id, limit=limit, cursor=cursor, offset=offset, request_options=request_options
        )
        return _response.data

    def get_backtest_trial(
        self, job_id: str, trial_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BacktestTrialDetailResponse:
        """
        Parameters
        ----------
        job_id : str

        trial_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BacktestTrialDetailResponse
            Trial evidence bundle

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.backtests.get_backtest_trial(
            job_id="job_id",
            trial_id="trial_id",
        )
        """
        _response = self._raw_client.get_backtest_trial(job_id, trial_id, request_options=request_options)
        return _response.data

    def cancel_backtest_job(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelBacktestJobResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelBacktestJobResponse
            Cancellation request result

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.backtests.cancel_backtest_job(
            job_id="job_id",
        )
        """
        _response = self._raw_client.cancel_backtest_job(job_id, request_options=request_options)
        return _response.data

    def stream_backtest_job_events(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[TrialEvent]:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[TrialEvent]
            Server-Sent Events carrying backtest progress and terminal state

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        response = client.backtests.stream_backtest_job_events(
            job_id="job_id",
        )
        for chunk in response:
            yield chunk
        """
        with self._raw_client.stream_backtest_job_events(job_id, request_options=request_options) as r:
            yield from r.data


class AsyncBacktestsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBacktestsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBacktestsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBacktestsClient
        """
        return self._raw_client

    async def get_backtests_availability(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BacktestsAvailability:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BacktestsAvailability
            Backtest launch options

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.backtests.get_backtests_availability()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_backtests_availability(request_options=request_options)
        return _response.data

    async def list_backtest_jobs(
        self,
        *,
        mode: typing.Optional[str] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBacktestJobsResponse:
        """
        Parameters
        ----------
        mode : typing.Optional[str]

        status : typing.Optional[str]

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque position returned as `next_cursor` by the preceding page.

        offset : typing.Optional[int]
            Deprecated compatibility input. Pass the opaque `cursor` instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBacktestJobsResponse
            Backtest jobs

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.backtests.list_backtest_jobs()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_backtest_jobs(
            mode=mode, status=status, limit=limit, cursor=cursor, offset=offset, request_options=request_options
        )
        return _response.data

    async def create_backtest_job(
        self,
        *,
        name: str,
        recipe: CreateBacktestJobRequestRecipe,
        idempotency_key: typing.Optional[str] = None,
        cases: typing.Optional[typing.Sequence[CreateBacktestJobRequestCasesItem]] = OMIT,
        evaluator_profile_id: typing.Optional[str] = OMIT,
        n_concurrent: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateBacktestJobResponse:
        """
        Returns 202 after the durable job and its trials have been admitted.

        Parameters
        ----------
        name : str

        recipe : CreateBacktestJobRequestRecipe

        idempotency_key : typing.Optional[str]
            Optional caller-generated key for safely retrying a mutation after an ambiguous network failure. Keys are scoped to the authenticated tenant and operation. Reusing a key with the same payload returns the original successful result; reusing it with a different payload returns 409.

        cases : typing.Optional[typing.Sequence[CreateBacktestJobRequestCasesItem]]

        evaluator_profile_id : typing.Optional[str]

        n_concurrent : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateBacktestJobResponse
            Backtest job accepted

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle
        from chroniclelabs.backtests import (
            CreateBacktestJobRequestRecipe,
            CreateBacktestJobRequestRecipeAgentsItem,
            CreateBacktestJobRequestRecipeData,
            CreateBacktestJobRequestRecipeDataScenariosItem,
            CreateBacktestJobRequestRecipeDataSourcesItem,
            CreateBacktestJobRequestRecipeGradersItem,
        )

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.backtests.create_backtest_job(
                name="name",
                recipe=CreateBacktestJobRequestRecipe(
                    agents=[
                        CreateBacktestJobRequestRecipeAgentsItem(
                            hue="hue",
                            id="id",
                            label="label",
                            notes="notes",
                        )
                    ],
                    data=CreateBacktestJobRequestRecipeData(
                        kind="composed",
                        scenarios=[
                            CreateBacktestJobRequestRecipeDataScenariosItem(
                                count=1,
                                id="id",
                                kind="adversarial",
                                label="label",
                            )
                        ],
                        sources=[
                            CreateBacktestJobRequestRecipeDataSourcesItem(
                                count=1,
                                id="id",
                                kind="prod",
                                label="label",
                            )
                        ],
                    ),
                    graders=[
                        CreateBacktestJobRequestRecipeGradersItem(
                            id="id",
                            kind="rubric",
                            label="label",
                            source="proposed",
                            weight="low",
                        )
                    ],
                    mode="replay",
                    name="name",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_backtest_job(
            name=name,
            recipe=recipe,
            idempotency_key=idempotency_key,
            cases=cases,
            evaluator_profile_id=evaluator_profile_id,
            n_concurrent=n_concurrent,
            request_options=request_options,
        )
        return _response.data

    async def get_backtest_job(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BacktestJobDetailResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BacktestJobDetailResponse
            Backtest job

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.backtests.get_backtest_job(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_backtest_job(job_id, request_options=request_options)
        return _response.data

    async def list_backtest_job_trials(
        self,
        job_id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListBacktestJobTrialsResponse:
        """
        Parameters
        ----------
        job_id : str

        limit : typing.Optional[int]

        cursor : typing.Optional[str]
            Opaque position returned as `next_cursor` by the preceding page.

        offset : typing.Optional[int]
            Deprecated compatibility input. Pass the opaque `cursor` instead.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListBacktestJobTrialsResponse
            Backtest trials and rewards

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.backtests.list_backtest_job_trials(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_backtest_job_trials(
            job_id, limit=limit, cursor=cursor, offset=offset, request_options=request_options
        )
        return _response.data

    async def get_backtest_trial(
        self, job_id: str, trial_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> BacktestTrialDetailResponse:
        """
        Parameters
        ----------
        job_id : str

        trial_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BacktestTrialDetailResponse
            Trial evidence bundle

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.backtests.get_backtest_trial(
                job_id="job_id",
                trial_id="trial_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_backtest_trial(job_id, trial_id, request_options=request_options)
        return _response.data

    async def cancel_backtest_job(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelBacktestJobResponse:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelBacktestJobResponse
            Cancellation request result

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.backtests.cancel_backtest_job(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_backtest_job(job_id, request_options=request_options)
        return _response.data

    async def stream_backtest_job_events(
        self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[TrialEvent]:
        """
        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[TrialEvent]
            Server-Sent Events carrying backtest progress and terminal state

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = client.backtests.stream_backtest_job_events(
                job_id="job_id",
            )
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.stream_backtest_job_events(job_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk
