# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.compile_environment_response import CompileEnvironmentResponse
from ..types.environment_response import EnvironmentResponse
from ..types.environment_spec import EnvironmentSpec
from ..types.environment_version_record import EnvironmentVersionRecord
from ..types.environment_version_response import EnvironmentVersionResponse
from ..types.environment_version_status import EnvironmentVersionStatus
from ..types.list_environments_response import ListEnvironmentsResponse
from .raw_client import AsyncRawEnvironmentsClient, RawEnvironmentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EnvironmentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEnvironmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEnvironmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEnvironmentsClient
        """
        return self._raw_client

    def list_environments(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListEnvironmentsResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEnvironmentsResponse
            Environments

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.environments.list_environments()
        """
        _response = self._raw_client.list_environments(request_options=request_options)
        return _response.data

    def create_environment(
        self,
        *,
        slug: str,
        label: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnvironmentResponse:
        """
        Parameters
        ----------
        slug : str

        label : str

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentResponse
            Environment created

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.environments.create_environment(
            slug="support-sandbox",
            label="Support sandbox",
            description="Isolated environment for support-agent backtests.",
        )
        """
        _response = self._raw_client.create_environment(
            slug=slug, label=label, description=description, request_options=request_options
        )
        return _response.data

    def get_environment(
        self, environment_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EnvironmentResponse:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentResponse
            Environment and versions

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.environments.get_environment(
            environment_id="environment_id",
        )
        """
        _response = self._raw_client.get_environment(environment_id, request_options=request_options)
        return _response.data

    def list_environment_versions(
        self, environment_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[EnvironmentVersionRecord]:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EnvironmentVersionRecord]
            Environment versions

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.environments.list_environment_versions(
            environment_id="environment_id",
        )
        """
        _response = self._raw_client.list_environment_versions(environment_id, request_options=request_options)
        return _response.data

    def create_environment_version(
        self,
        environment_id: str,
        *,
        version: str,
        spec: typing.Optional[EnvironmentSpec] = OMIT,
        status: typing.Optional[EnvironmentVersionStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnvironmentVersionResponse:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        version : str

        spec : typing.Optional[EnvironmentSpec]

        status : typing.Optional[EnvironmentVersionStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentVersionResponse
            Environment version created

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.environments.create_environment_version(
            environment_id="environment_id",
            version="version",
        )
        """
        _response = self._raw_client.create_environment_version(
            environment_id, version=version, spec=spec, status=status, request_options=request_options
        )
        return _response.data

    def get_environment_version(
        self, environment_id: str, version_selector: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EnvironmentVersionResponse:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        version_selector : str
            Environment-version ID or version label.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentVersionResponse
            Environment version

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.environments.get_environment_version(
            environment_id="environment_id",
            version_selector="version_selector",
        )
        """
        _response = self._raw_client.get_environment_version(
            environment_id, version_selector, request_options=request_options
        )
        return _response.data

    def compile_environment_version(
        self,
        environment_id: str,
        version_selector: str,
        *,
        dataset_snapshot_id: str,
        scenario_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CompileEnvironmentResponse:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        version_selector : str
            Environment-version ID or version label.

        dataset_snapshot_id : str

        scenario_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompileEnvironmentResponse
            Compiled environment bundle

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.environments.compile_environment_version(
            environment_id="environment_id",
            version_selector="version_selector",
            dataset_snapshot_id="datasetSnapshotId",
            scenario_id="scenarioId",
        )
        """
        _response = self._raw_client.compile_environment_version(
            environment_id,
            version_selector,
            dataset_snapshot_id=dataset_snapshot_id,
            scenario_id=scenario_id,
            request_options=request_options,
        )
        return _response.data


class AsyncEnvironmentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEnvironmentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEnvironmentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEnvironmentsClient
        """
        return self._raw_client

    async def list_environments(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListEnvironmentsResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListEnvironmentsResponse
            Environments

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.list_environments()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_environments(request_options=request_options)
        return _response.data

    async def create_environment(
        self,
        *,
        slug: str,
        label: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnvironmentResponse:
        """
        Parameters
        ----------
        slug : str

        label : str

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentResponse
            Environment created

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.create_environment(
                slug="support-sandbox",
                label="Support sandbox",
                description="Isolated environment for support-agent backtests.",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_environment(
            slug=slug, label=label, description=description, request_options=request_options
        )
        return _response.data

    async def get_environment(
        self, environment_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EnvironmentResponse:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentResponse
            Environment and versions

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.get_environment(
                environment_id="environment_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_environment(environment_id, request_options=request_options)
        return _response.data

    async def list_environment_versions(
        self, environment_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[EnvironmentVersionRecord]:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[EnvironmentVersionRecord]
            Environment versions

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.list_environment_versions(
                environment_id="environment_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_environment_versions(environment_id, request_options=request_options)
        return _response.data

    async def create_environment_version(
        self,
        environment_id: str,
        *,
        version: str,
        spec: typing.Optional[EnvironmentSpec] = OMIT,
        status: typing.Optional[EnvironmentVersionStatus] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EnvironmentVersionResponse:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        version : str

        spec : typing.Optional[EnvironmentSpec]

        status : typing.Optional[EnvironmentVersionStatus]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentVersionResponse
            Environment version created

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.create_environment_version(
                environment_id="environment_id",
                version="version",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_environment_version(
            environment_id, version=version, spec=spec, status=status, request_options=request_options
        )
        return _response.data

    async def get_environment_version(
        self, environment_id: str, version_selector: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EnvironmentVersionResponse:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        version_selector : str
            Environment-version ID or version label.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EnvironmentVersionResponse
            Environment version

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.get_environment_version(
                environment_id="environment_id",
                version_selector="version_selector",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_environment_version(
            environment_id, version_selector, request_options=request_options
        )
        return _response.data

    async def compile_environment_version(
        self,
        environment_id: str,
        version_selector: str,
        *,
        dataset_snapshot_id: str,
        scenario_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CompileEnvironmentResponse:
        """
        Parameters
        ----------
        environment_id : str
            Environment ID or slug.

        version_selector : str
            Environment-version ID or version label.

        dataset_snapshot_id : str

        scenario_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CompileEnvironmentResponse
            Compiled environment bundle

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.environments.compile_environment_version(
                environment_id="environment_id",
                version_selector="version_selector",
                dataset_snapshot_id="datasetSnapshotId",
                scenario_id="scenarioId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.compile_environment_version(
            environment_id,
            version_selector,
            dataset_snapshot_id=dataset_snapshot_id,
            scenario_id=scenario_id,
            request_options=request_options,
        )
        return _response.data
