# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .accepted_response import AcceptedResponse
    from .create_link_response import CreateLinkResponse
    from .entity_info import EntityInfo
    from .entity_list_response import EntityListResponse
    from .entity_ref import EntityRef
    from .entity_type_info import EntityTypeInfo
    from .entity_type_list_response import EntityTypeListResponse
    from .error_response import ErrorResponse
    from .error_response_code import ErrorResponseCode
    from .event import Event
    from .event_list_response import EventListResponse
    from .event_page import EventPage
    from .event_result import EventResult
    from .ingest_request import IngestRequest
    from .ingest_response import IngestResponse
    from .link_entity_response import LinkEntityResponse
    from .media_attachment import MediaAttachment
    from .pending_entity_ref import PendingEntityRef
    from .signal_request import SignalRequest
    from .source_info import SourceInfo
    from .source_list_response import SourceListResponse
    from .source_schema import SourceSchema
    from .span_request import SpanRequest
    from .status_response import StatusResponse
    from .trace_request import TraceRequest
_dynamic_imports: typing.Dict[str, str] = {
    "AcceptedResponse": ".accepted_response",
    "CreateLinkResponse": ".create_link_response",
    "EntityInfo": ".entity_info",
    "EntityListResponse": ".entity_list_response",
    "EntityRef": ".entity_ref",
    "EntityTypeInfo": ".entity_type_info",
    "EntityTypeListResponse": ".entity_type_list_response",
    "ErrorResponse": ".error_response",
    "ErrorResponseCode": ".error_response_code",
    "Event": ".event",
    "EventListResponse": ".event_list_response",
    "EventPage": ".event_page",
    "EventResult": ".event_result",
    "IngestRequest": ".ingest_request",
    "IngestResponse": ".ingest_response",
    "LinkEntityResponse": ".link_entity_response",
    "MediaAttachment": ".media_attachment",
    "PendingEntityRef": ".pending_entity_ref",
    "SignalRequest": ".signal_request",
    "SourceInfo": ".source_info",
    "SourceListResponse": ".source_list_response",
    "SourceSchema": ".source_schema",
    "SpanRequest": ".span_request",
    "StatusResponse": ".status_response",
    "TraceRequest": ".trace_request",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AcceptedResponse",
    "CreateLinkResponse",
    "EntityInfo",
    "EntityListResponse",
    "EntityRef",
    "EntityTypeInfo",
    "EntityTypeListResponse",
    "ErrorResponse",
    "ErrorResponseCode",
    "Event",
    "EventListResponse",
    "EventPage",
    "EventResult",
    "IngestRequest",
    "IngestResponse",
    "LinkEntityResponse",
    "MediaAttachment",
    "PendingEntityRef",
    "SignalRequest",
    "SourceInfo",
    "SourceListResponse",
    "SourceSchema",
    "SpanRequest",
    "StatusResponse",
    "TraceRequest",
]
