# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .add_task_from_trace_response_membership_purpose import AddTaskFromTraceResponseMembershipPurpose
from .add_task_from_trace_response_membership_split import AddTaskFromTraceResponseMembershipSplit
from .add_task_from_trace_response_membership_subject_kind import AddTaskFromTraceResponseMembershipSubjectKind


class AddTaskFromTraceResponseMembership(UniversalBaseModel):
    """
    The compact membership projection returned to Dataset and Timeline clients.
    """

    added_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="addedAt"), pydantic.Field(alias="addedAt")
    ] = None
    dataset_id: typing_extensions.Annotated[str, FieldMetadata(alias="datasetId"), pydantic.Field(alias="datasetId")]
    dataset_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="datasetName"), pydantic.Field(alias="datasetName")
    ]
    event_count: typing_extensions.Annotated[int, FieldMetadata(alias="eventCount"), pydantic.Field(alias="eventCount")]
    id: str
    note: typing.Optional[str] = None
    purpose: typing.Optional[AddTaskFromTraceResponseMembershipPurpose] = pydantic.Field(default=None)
    """
    Intended use of a dataset — drives the colored badge on the picker and lets apps route additions to the right backend (eval suite, training set, replay corpus, manual review queue).
    """

    refresh_available: typing_extensions.Annotated[
        bool, FieldMetadata(alias="refreshAvailable"), pydantic.Field(alias="refreshAvailable")
    ]
    revision: int
    split: typing.Optional[AddTaskFromTraceResponseMembershipSplit] = pydantic.Field(default=None)
    """
    Train / validation / test split assignment.
    """

    subject_id: typing_extensions.Annotated[str, FieldMetadata(alias="subjectId"), pydantic.Field(alias="subjectId")]
    subject_kind: typing_extensions.Annotated[
        AddTaskFromTraceResponseMembershipSubjectKind,
        FieldMetadata(alias="subjectKind"),
        pydantic.Field(
            alias="subjectKind",
            description="The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service.",
        ),
    ]
    """
    The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service.
    """

    trace_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="traceId"),
        pydantic.Field(
            alias="traceId",
            description="Compatibility identity consumed by the Timeline picker. For an event membership this is the event id.",
        ),
    ]
    """
    Compatibility identity consumed by the Timeline picker. For an event membership this is the event id.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
