# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .add_task_from_trace_response_dataset import AddTaskFromTraceResponseDataset
from .add_task_from_trace_response_membership import AddTaskFromTraceResponseMembership


class AddTaskFromTraceResponse(UniversalBaseModel):
    dataset: AddTaskFromTraceResponseDataset
    membership: AddTaskFromTraceResponseMembership = pydantic.Field()
    """
    The compact membership projection returned to Dataset and Timeline clients.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
