# This file was auto-generated by Fern from our API Definition.

import typing

AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind = typing.Union[
    typing.Literal["input", "tool", "model", "branch", "output"], typing.Any
]
