# This file was auto-generated by Fern from our API Definition.

import typing

AgentVersionSummaryArtifactWorkflowGraphPreviewNodesItemKind = typing.Union[
    typing.Literal["input", "tool", "model", "branch", "output"], typing.Any
]
