# This file was auto-generated by Fern from our API Definition.

import typing

AgentSnapshotVersionsItemArtifactKnowledgeSourcesItemKind = typing.Union[
    typing.Literal["vector", "doc", "table", "graph"], typing.Any
]
