# This file was auto-generated by Fern from our API Definition.

import typing

AgentSnapshotVersionsItemArtifactFramework = typing.Union[
    typing.Literal[
        "vercel-ai-sdk",
        "openai-agents",
        "langchain",
        "mastra",
        "langchain-python",
        "llamaindex",
        "crewai",
        "smolagents",
        "pydantic-ai",
        "strands",
        "google-adk",
        "openai-agents-python",
        "autogen",
        "eve",
        "salesforce-agentforce",
    ],
    typing.Any,
]
