# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AgentSnapshotRunsItemResponseUsage(UniversalBaseModel):
    cached_input_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="cachedInputTokens"), pydantic.Field(alias="cachedInputTokens")
    ] = None
    input_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="inputTokens"), pydantic.Field(alias="inputTokens")
    ] = None
    output_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="outputTokens"), pydantic.Field(alias="outputTokens")
    ] = None
    reasoning_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="reasoningTokens"), pydantic.Field(alias="reasoningTokens")
    ] = None
    total_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="totalTokens"), pydantic.Field(alias="totalTokens")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
