# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_snapshot_versions_item_artifact_workflow_graph_preview_edges_item import (
    AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewEdgesItem,
)
from .agent_snapshot_versions_item_artifact_workflow_graph_preview_nodes_item import (
    AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItem,
)


class AgentSnapshotVersionsItemArtifactWorkflowGraphPreview(UniversalBaseModel):
    edges: typing.List[AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewEdgesItem]
    nodes: typing.List[AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
