# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agent_snapshot_versions_item_artifact import AgentSnapshotVersionsItemArtifact
from .agent_snapshot_versions_item_status import AgentSnapshotVersionsItemStatus


class AgentSnapshotVersionsItem(UniversalBaseModel):
    artifact: AgentSnapshotVersionsItemArtifact
    last_run_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastRunAt"), pydantic.Field(alias="lastRunAt")
    ] = None
    mean_duration_ms: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="meanDurationMs"), pydantic.Field(alias="meanDurationMs")
    ] = None
    p95duration_ms: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="p95DurationMs"), pydantic.Field(alias="p95DurationMs")
    ] = None
    resolved_model_ids: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="resolvedModelIds"), pydantic.Field(alias="resolvedModelIds")
    ]
    run_count: typing_extensions.Annotated[int, FieldMetadata(alias="runCount"), pydantic.Field(alias="runCount")]
    status: AgentSnapshotVersionsItemStatus
    success_rate: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="successRate"),
        pydantic.Field(alias="successRate", description="Successful runs / total runs (0..1)."),
    ]
    """
    Successful runs / total runs (0..1).
    """

    total_tokens: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="totalTokens"), pydantic.Field(alias="totalTokens")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
