# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class AgentVersionSummaryArtifactInputContractPreview(UniversalBaseModel):
    """
    Compact preview of the input contract this artifact expects.
    """

    example: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Representative example payload.
    """

    schema_summary: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="schemaSummary"),
        pydantic.Field(alias="schemaSummary", description="One-line shape summary."),
    ] = None
    """
    One-line shape summary.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
