# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agent_snapshot_runs_item_error import AgentSnapshotRunsItemError
from .agent_snapshot_runs_item_operation import AgentSnapshotRunsItemOperation
from .agent_snapshot_runs_item_prepared_call import AgentSnapshotRunsItemPreparedCall
from .agent_snapshot_runs_item_response import AgentSnapshotRunsItemResponse
from .agent_snapshot_runs_item_status import AgentSnapshotRunsItemStatus
from .agent_snapshot_runs_item_tool_calls_item import AgentSnapshotRunsItemToolCallsItem


class AgentSnapshotRunsItem(UniversalBaseModel):
    artifact_id: typing_extensions.Annotated[str, FieldMetadata(alias="artifactId"), pydantic.Field(alias="artifactId")]
    call_options_hash: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="callOptionsHash"), pydantic.Field(alias="callOptionsHash")
    ] = None
    config_hash: typing_extensions.Annotated[str, FieldMetadata(alias="configHash"), pydantic.Field(alias="configHash")]
    duration_ms: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="durationMs"), pydantic.Field(alias="durationMs")
    ] = None
    error: typing.Optional[AgentSnapshotRunsItemError] = None
    finished_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="finishedAt"), pydantic.Field(alias="finishedAt")
    ] = None
    input_hash: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="inputHash"), pydantic.Field(alias="inputHash")
    ] = None
    operation: AgentSnapshotRunsItemOperation
    prepared_call: typing_extensions.Annotated[
        typing.Optional[AgentSnapshotRunsItemPreparedCall],
        FieldMetadata(alias="preparedCall"),
        pydantic.Field(alias="preparedCall"),
    ] = None
    response: typing.Optional[AgentSnapshotRunsItemResponse] = None
    run_id: typing_extensions.Annotated[str, FieldMetadata(alias="runId"), pydantic.Field(alias="runId")]
    schema_version: typing_extensions.Annotated[
        str, FieldMetadata(alias="schemaVersion"), pydantic.Field(alias="schemaVersion")
    ]
    started_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="startedAt"), pydantic.Field(alias="startedAt")
    ]
    status: AgentSnapshotRunsItemStatus
    tool_calls: typing_extensions.Annotated[
        typing.List[AgentSnapshotRunsItemToolCallsItem],
        FieldMetadata(alias="toolCalls"),
        pydantic.Field(alias="toolCalls"),
    ]
    trace: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
