# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .agent_snapshot_versions_item_artifact_workflow_graph_preview_nodes_item_kind import (
    AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind,
)


class AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItem(UniversalBaseModel):
    id: str
    kind: AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind
    label: str
    tool_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="toolName"),
        pydantic.Field(alias="toolName", description="Optional tool name reference for tool nodes."),
    ] = None
    """
    Optional tool name reference for tool nodes.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
