# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .backtests_availability_agents_item import BacktestsAvailabilityAgentsItem
from .backtests_availability_dataset_snapshots_value import BacktestsAvailabilityDatasetSnapshotsValue
from .backtests_availability_datasets_item import BacktestsAvailabilityDatasetsItem
from .backtests_availability_environments_item import BacktestsAvailabilityEnvironmentsItem


class BacktestsAvailability(UniversalBaseModel):
    """
    Returned by `GET /api/platform/backtests/availability`. Matches the frontend's `BacktestsAvailability`. Datasets, environments, and agents come from their respective domain crates' types — the IDs in these slices are what the recipe references.
    """

    agents: typing.List[BacktestsAvailabilityAgentsItem]
    dataset_snapshots: typing_extensions.Annotated[
        typing.Dict[str, BacktestsAvailabilityDatasetSnapshotsValue],
        FieldMetadata(alias="datasetSnapshots"),
        pydantic.Field(alias="datasetSnapshots"),
    ]
    datasets: typing.List[BacktestsAvailabilityDatasetsItem]
    environments: typing.List[BacktestsAvailabilityEnvironmentsItem] = pydantic.Field()
    """
    Environment row identities + status. Detailed snapshot lives behind `GET /api/platform/environments/:id`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
