# This file was auto-generated by Fern from our API Definition.

import typing

BacktestTrialDetailResponseScorersItemGraderCodeLanguage = typing.Union[
    typing.Literal["python", "typescript"], typing.Any
]
