# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .backtest_trial_detail_response_artifacts_item_kind import BacktestTrialDetailResponseArtifactsItemKind


class BacktestTrialDetailResponseArtifactsItem(UniversalBaseModel):
    content_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="contentType"), pydantic.Field(alias="contentType")
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    id: str
    kind: BacktestTrialDetailResponseArtifactsItemKind = pydantic.Field()
    """
    Row projection of `"BacktestArtifact"`.
    """

    path: str
    size_bytes: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="sizeBytes"), pydantic.Field(alias="sizeBytes")
    ] = None
    trial_id: typing_extensions.Annotated[str, FieldMetadata(alias="trialId"), pydantic.Field(alias="trialId")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
