# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .backtest_trial_detail_response_artifacts_item import BacktestTrialDetailResponseArtifactsItem
from .backtest_trial_detail_response_scorers_item import BacktestTrialDetailResponseScorersItem
from .backtest_trial_detail_response_steps_item import BacktestTrialDetailResponseStepsItem
from .backtest_trial_detail_response_trial import BacktestTrialDetailResponseTrial


class BacktestTrialDetailResponse(UniversalBaseModel):
    """
    Returned by `GET /api/platform/backtests/jobs/:id/trials/:trialId`. Everything the trial detail view renders in one round trip.
    """

    artifacts: typing.List[BacktestTrialDetailResponseArtifactsItem]
    rewards: typing.Dict[str, float] = pydantic.Field()
    """
    Reward name → score for this trial.
    """

    scorers: typing.List[BacktestTrialDetailResponseScorersItem] = pydantic.Field()
    """
    Scorers bound to this trial's task (frozen verifiers first, then recipe-level graders), in binding order.
    """

    steps: typing.List[BacktestTrialDetailResponseStepsItem] = pydantic.Field()
    """
    Timeline steps ordered by ordinal.
    """

    trial: BacktestTrialDetailResponseTrial = pydantic.Field()
    """
    Row projection of `"BacktestTrial"`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
