# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .backtest_job_detail_response_job_mode import BacktestJobDetailResponseJobMode
from .backtest_job_detail_response_job_retry_config import BacktestJobDetailResponseJobRetryConfig
from .backtest_job_detail_response_job_sandbox_driver import BacktestJobDetailResponseJobSandboxDriver
from .backtest_job_detail_response_job_status import BacktestJobDetailResponseJobStatus


class BacktestJobDetailResponseJob(UniversalBaseModel):
    """
    Row projection of `"BacktestJob"`.
    """

    completed_trials: typing_extensions.Annotated[
        int, FieldMetadata(alias="completedTrials"), pydantic.Field(alias="completedTrials")
    ]
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    created_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="createdBy"), pydantic.Field(alias="createdBy")
    ] = None
    dataset_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="datasetId"),
        pydantic.Field(alias="datasetId", description="Mutable Dataset selected when the job was launched."),
    ] = None
    """
    Mutable Dataset selected when the job was launched.
    """

    dataset_version_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="datasetVersionId"),
        pydantic.Field(
            alias="datasetVersionId",
            description="Immutable Dataset Version used to compile this job's cases. Once set, later working-copy edits cannot alter the run inputs.",
        ),
    ] = None
    """
    Immutable Dataset Version used to compile this job's cases. Once set, later working-copy edits cannot alter the run inputs.
    """

    exception_kind: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="exceptionKind"), pydantic.Field(alias="exceptionKind")
    ] = None
    failed_trials: typing_extensions.Annotated[
        int, FieldMetadata(alias="failedTrials"), pydantic.Field(alias="failedTrials")
    ]
    finished_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="finishedAt"), pydantic.Field(alias="finishedAt")
    ] = None
    id: str
    mode: BacktestJobDetailResponseJobMode
    n_concurrent: typing_extensions.Annotated[
        int, FieldMetadata(alias="nConcurrent"), pydantic.Field(alias="nConcurrent")
    ]
    name: str
    recipe: typing.Any
    retry_config: typing_extensions.Annotated[
        typing.Optional[BacktestJobDetailResponseJobRetryConfig],
        FieldMetadata(alias="retryConfig"),
        pydantic.Field(
            alias="retryConfig",
            description="Retry policy applied to transient trial failures (network errors, sandbox-create timeouts). Mirrors Harbor's `RetryConfig`. Pass `null` on the wire (`None` here) to fall back to defaults.",
        ),
    ] = None
    """
    Retry policy applied to transient trial failures (network errors, sandbox-create timeouts). Mirrors Harbor's `RetryConfig`. Pass `null` on the wire (`None` here) to fall back to defaults.
    """

    sandbox_driver: typing_extensions.Annotated[
        BacktestJobDetailResponseJobSandboxDriver,
        FieldMetadata(alias="sandboxDriver"),
        pydantic.Field(
            alias="sandboxDriver",
            description="Sandbox driver selected by trusted server policy at submit time. Echoed onto the `BacktestJob.sandboxDriver` column so persisted jobs record which implementation backed the `Sandbox` trait.",
        ),
    ]
    """
    Sandbox driver selected by trusted server policy at submit time. Echoed onto the `BacktestJob.sandboxDriver` column so persisted jobs record which implementation backed the `Sandbox` trait.
    """

    scheduled_for: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="scheduledFor"), pydantic.Field(alias="scheduledFor")
    ] = None
    started_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="startedAt"), pydantic.Field(alias="startedAt")
    ] = None
    status: BacktestJobDetailResponseJobStatus = pydantic.Field()
    """
    Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the `status` column in `migrations/013_create_backtest_runtime.sql`.
    """

    tenant_id: typing_extensions.Annotated[str, FieldMetadata(alias="tenantId"), pydantic.Field(alias="tenantId")]
    total_trials: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="totalTrials"), pydantic.Field(alias="totalTrials")
    ] = None
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]
    verdict: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
