# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class BacktestJobDetailResponseJobRetryConfig(UniversalBaseModel):
    """
    Retry policy applied to transient trial failures (network errors, sandbox-create timeouts). Mirrors Harbor's `RetryConfig`. Pass `null` on the wire (`None` here) to fall back to defaults.
    """

    exclude_exceptions: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="excludeExceptions"),
        pydantic.Field(
            alias="excludeExceptions",
            description="Exception kinds that explicitly should not be retried even if otherwise matched by `include_exceptions`.",
        ),
    ] = None
    """
    Exception kinds that explicitly should not be retried even if otherwise matched by `include_exceptions`.
    """

    include_exceptions: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="includeExceptions"),
        pydantic.Field(
            alias="includeExceptions",
            description='When set, only exception kinds in this list trigger a retry. `None` means "retry every transient kind".',
        ),
    ] = None
    """
    When set, only exception kinds in this list trigger a retry. `None` means "retry every transient kind".
    """

    max_retries: typing_extensions.Annotated[int, FieldMetadata(alias="maxRetries"), pydantic.Field(alias="maxRetries")]
    max_wait_sec: typing_extensions.Annotated[
        float, FieldMetadata(alias="maxWaitSec"), pydantic.Field(alias="maxWaitSec")
    ]
    min_wait_sec: typing_extensions.Annotated[
        float, FieldMetadata(alias="minWaitSec"), pydantic.Field(alias="minWaitSec")
    ]
    wait_multiplier: typing_extensions.Annotated[
        float, FieldMetadata(alias="waitMultiplier"), pydantic.Field(alias="waitMultiplier")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
