# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .backtest_trial_detail_response_scorers_item_grader import BacktestTrialDetailResponseScorersItemGrader


class BacktestTrialDetailResponseScorersItem(UniversalBaseModel):
    """
    A scorer as the trial view needs it: the frozen grader snapshot the reward key points at, plus the reward key itself so the UI can join scores to names without reconstructing `grader_<id>`.

    Resolved from the job's pinned Dataset Version items (task verifiers, `source: dataset`) and the recipe's own grader list.
    """

    grader: BacktestTrialDetailResponseScorersItemGrader
    reward_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="rewardKey"),
        pydantic.Field(
            alias="rewardKey", description="Reward key this scorer's score is stored under (`grader_<id>`)."
        ),
    ]
    """
    Reward key this scorer's score is stored under (`grader_<id>`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
