# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .backtests_availability_agents_item_framework import BacktestsAvailabilityAgentsItemFramework
from .backtests_availability_agents_item_model import BacktestsAvailabilityAgentsItemModel


class BacktestsAvailabilityAgentsItem(UniversalBaseModel):
    capability_tags: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="capabilityTags"), pydantic.Field(alias="capabilityTags")
    ] = None
    category: typing.Optional[str] = None
    description: typing.Optional[str] = None
    environment: typing.Optional[str] = None
    framework: BacktestsAvailabilityAgentsItemFramework = pydantic.Field()
    """
    Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.).
    """

    last_drift_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="lastDriftAt"),
        pydantic.Field(alias="lastDriftAt", description="Last drift event, if any."),
    ] = None
    """
    Last drift event, if any.
    """

    last_run_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastRunAt"), pydantic.Field(alias="lastRunAt")
    ] = None
    latest_version: typing_extensions.Annotated[
        str, FieldMetadata(alias="latestVersion"), pydantic.Field(alias="latestVersion")
    ]
    model: BacktestsAvailabilityAgentsItemModel
    model_label: typing_extensions.Annotated[str, FieldMetadata(alias="modelLabel"), pydantic.Field(alias="modelLabel")]
    name: str
    owner: typing.Optional[str] = None
    persona_summary: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="personaSummary"), pydantic.Field(alias="personaSummary")
    ] = None
    playground_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="playgroundUrl"), pydantic.Field(alias="playgroundUrl")
    ] = None
    purpose: typing.Optional[str] = None
    runbook_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="runbookUrl"), pydantic.Field(alias="runbookUrl")
    ] = None
    success_rate: typing_extensions.Annotated[
        float, FieldMetadata(alias="successRate"), pydantic.Field(alias="successRate")
    ]
    total_runs: typing_extensions.Annotated[int, FieldMetadata(alias="totalRuns"), pydantic.Field(alias="totalRuns")]
    version_count: typing_extensions.Annotated[
        int, FieldMetadata(alias="versionCount"), pydantic.Field(alias="versionCount")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
