# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .backtest_trial_detail_response_steps_item_actor import BacktestTrialDetailResponseStepsItemActor
from .backtest_trial_detail_response_steps_item_kind import BacktestTrialDetailResponseStepsItemKind
from .backtest_trial_detail_response_steps_item_status import BacktestTrialDetailResponseStepsItemStatus


class BacktestTrialDetailResponseStepsItem(UniversalBaseModel):
    """
    Row projection of `"BacktestTrialStep"`.
    """

    actor: BacktestTrialDetailResponseStepsItemActor = pydantic.Field()
    """
    Who performed a step; one timeline lane per actor.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    ended_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="endedAt"),
        pydantic.Field(alias="endedAt", description="`None` for instantaneous steps (seed events, state changes)."),
    ] = None
    """
    `None` for instantaneous steps (seed events, state changes).
    """

    grader_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="graderId"),
        pydantic.Field(alias="graderId", description="Frozen verifier id (or recipe grader id) for `grade` steps."),
    ] = None
    """
    Frozen verifier id (or recipe grader id) for `grade` steps.
    """

    id: str
    kind: BacktestTrialDetailResponseStepsItemKind = pydantic.Field()
    """
    What a step is. Drives the glyph on the timeline and which detail renderer opens when the span is clicked.
    """

    ordinal: int = pydantic.Field()
    """
    Position within the trial; steps are returned ordered by it.
    """

    payload: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Free-form detail: `request`/`response` for tool calls, `text` for messages, `reasoning` for judge grades, and so on.
    """

    score: typing.Optional[float] = pydantic.Field(default=None)
    """
    Grader score in `[0, 1]` for `grade` steps.
    """

    started_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="startedAt"), pydantic.Field(alias="startedAt")
    ]
    status: typing.Optional[BacktestTrialDetailResponseStepsItemStatus] = pydantic.Field(default=None)
    """
    Outcome colouring for a step. `None` renders neutral.
    """

    title: str
    trial_id: typing_extensions.Annotated[str, FieldMetadata(alias="trialId"), pydantic.Field(alias="trialId")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
