# This file was auto-generated by Fern from our API Definition.

import typing

BacktestTrialDetailResponseStepsItemActor = typing.Union[
    typing.Literal["environment", "agent", "verifier", "grader"], typing.Any
]
