# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class BacktestsAvailabilityEnvironmentsItem(UniversalBaseModel):
    """
    Reference to the environment a run will execute in. Mirrors the shape used by `EnvironmentsManager` (`SandboxEnvironment`) but without the heavy detail snapshot — the recipe only needs the identity + status to render summary chrome.
    """

    ephemeral: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this environment is a freshly cloned ephemeral sandbox or a saved long-lived environment.
    """

    id: str
    label: str
    snapshot_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="snapshotId"), pydantic.Field(alias="snapshotId")
    ] = None
    snapshot_label: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="snapshotLabel"), pydantic.Field(alias="snapshotLabel")
    ] = None
    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Mirror of `SandboxRuntimeStatus` strings ("started", "stopped", …). Kept loose so callers don't need to import the environments package.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
