# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CompileEnvironmentResponse(UniversalBaseModel):
    environment_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="environmentId"), pydantic.Field(alias="environmentId")
    ]
    environment_slug: typing_extensions.Annotated[
        str, FieldMetadata(alias="environmentSlug"), pydantic.Field(alias="environmentSlug")
    ]
    version_id: typing_extensions.Annotated[str, FieldMetadata(alias="versionId"), pydantic.Field(alias="versionId")]
    version: str
    tenant_id: typing_extensions.Annotated[str, FieldMetadata(alias="tenantId"), pydantic.Field(alias="tenantId")]
    dataset_snapshot_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="datasetSnapshotId"), pydantic.Field(alias="datasetSnapshotId")
    ]
    scenario_id: typing_extensions.Annotated[str, FieldMetadata(alias="scenarioId"), pydantic.Field(alias="scenarioId")]
    bundle_id: typing_extensions.Annotated[str, FieldMetadata(alias="bundleId"), pydantic.Field(alias="bundleId")]
    sha256: str
    uri: str
    package_uri: typing_extensions.Annotated[str, FieldMetadata(alias="packageUri"), pydantic.Field(alias="packageUri")]
    root_dir: typing_extensions.Annotated[str, FieldMetadata(alias="rootDir"), pydantic.Field(alias="rootDir")]
    size_bytes: typing_extensions.Annotated[int, FieldMetadata(alias="sizeBytes"), pydantic.Field(alias="sizeBytes")]
    warnings: typing.List[str]
    files: typing.List[str]
    manifest: typing.Dict[str, typing.Any]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
