# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .entity_info import EntityInfo


class EntityListResponse(UniversalBaseModel):
    """
    A stable page ordered by event count and entity ID.
    """

    data: typing.List[EntityInfo]
    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque position for the next request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
