# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EntityRef(UniversalBaseModel):
    """
    A stored entity reference, attributed and timestamped.
    """

    event_id: str
    entity_type: str
    entity_id: str
    created_by: str = pydantic.Field()
    """
    What created the reference, for example ingestion or a linker agent.
    """

    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
