# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .environment_version_record_spec import EnvironmentVersionRecordSpec
from .environment_version_record_status import EnvironmentVersionRecordStatus


class EnvironmentVersionRecord(UniversalBaseModel):
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    environment_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="environmentId"), pydantic.Field(alias="environmentId")
    ]
    id: str
    spec: EnvironmentVersionRecordSpec
    status: EnvironmentVersionRecordStatus
    tenant_id: typing_extensions.Annotated[str, FieldMetadata(alias="tenantId"), pydantic.Field(alias="tenantId")]
    version: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
