# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .media_attachment import MediaAttachment
from .pending_entity_ref import PendingEntityRef


class Event(UniversalBaseModel):
    """
    A stored event. Immutable once written.
    """

    event_id: str = pydantic.Field()
    """
    Time-ordered identifier, sorts in creation order.
    """

    org_id: str = pydantic.Field()
    """
    Organisation the event belongs to.
    """

    source: str
    topic: str
    event_type: str
    event_time: dt.datetime = pydantic.Field()
    """
    When the event happened at the source.
    """

    ingestion_time: dt.datetime = pydantic.Field()
    """
    When Chronicle received it.
    """

    payload: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Source-defined body. Free-form by design.
    """

    media: typing.Optional[MediaAttachment] = None
    entity_refs: typing.Optional[typing.List[PendingEntityRef]] = pydantic.Field(default=None)
    """
    Entity references supplied with the event at ingest time.
    """

    raw_body: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
