# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .event_result import EventResult


class EventListResponse(UniversalBaseModel):
    """
    A bounded page of events. An absent `next_cursor` means the page is final.
    """

    data: typing.List[EventResult]
    next_cursor: typing.Optional[str] = pydantic.Field(default=None)
    """
    Opaque position for the next request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
