# This file was auto-generated by Fern from our API Definition.

import typing

HashIndexEntryKind = typing.Union[
    typing.Literal[
        "agent.root",
        "prompt",
        "model.contract",
        "provider.options",
        "tool.contract",
        "runtime.policy",
        "dependency",
        "knowledge.contract",
        "workflow.graph",
        "effective.run",
        "provider.observation",
        "operational",
        "output",
    ],
    typing.Any,
]
