# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_backtest_job_trials_response_trials_item_exception import ListBacktestJobTrialsResponseTrialsItemException
from .list_backtest_job_trials_response_trials_item_status import ListBacktestJobTrialsResponseTrialsItemStatus
from .list_backtest_job_trials_response_trials_item_timings import ListBacktestJobTrialsResponseTrialsItemTimings


class ListBacktestJobTrialsResponseTrialsItem(UniversalBaseModel):
    """
    Row projection of `"BacktestTrial"`.
    """

    agent_id: typing_extensions.Annotated[str, FieldMetadata(alias="agentId"), pydantic.Field(alias="agentId")]
    agent_label: typing_extensions.Annotated[str, FieldMetadata(alias="agentLabel"), pydantic.Field(alias="agentLabel")]
    attempt: int
    case_cluster: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="caseCluster"), pydantic.Field(alias="caseCluster")
    ] = None
    case_id: typing_extensions.Annotated[str, FieldMetadata(alias="caseId"), pydantic.Field(alias="caseId")]
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    duration_ms: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="durationMs"), pydantic.Field(alias="durationMs")
    ] = None
    exception: typing.Optional[ListBacktestJobTrialsResponseTrialsItemException] = pydantic.Field(default=None)
    """
    Captured exception info for a failed trial. Mirrors Harbor's `ExceptionInfo` — kind for routing/retry, message for humans.
    """

    id: str
    instruction: typing.Optional[str] = pydantic.Field(default=None)
    """
    The case instruction this trial executed — persisted at launch so result surfaces can show the real prompt instead of reconstructing (or inventing) one client-side.
    """

    is_baseline: typing_extensions.Annotated[
        bool, FieldMetadata(alias="isBaseline"), pydantic.Field(alias="isBaseline")
    ]
    job_id: typing_extensions.Annotated[str, FieldMetadata(alias="jobId"), pydantic.Field(alias="jobId")]
    sandbox_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sandboxId"), pydantic.Field(alias="sandboxId")
    ] = None
    status: ListBacktestJobTrialsResponseTrialsItemStatus = pydantic.Field()
    """
    Lifecycle state of a single `BacktestTrial` (one (case × agent) cell).
    """

    tenant_id: typing_extensions.Annotated[str, FieldMetadata(alias="tenantId"), pydantic.Field(alias="tenantId")]
    timings: ListBacktestJobTrialsResponseTrialsItemTimings = pydantic.Field()
    """
    Per-phase timing bookkeeping. Each pair is `(started_at, finished_at)`; `None` until that phase starts/ends.
    """

    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
