# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .list_backtest_jobs_response_runs_item import ListBacktestJobsResponseRunsItem


class ListBacktestJobsResponse(UniversalBaseModel):
    has_more: typing_extensions.Annotated[bool, FieldMetadata(alias="hasMore"), pydantic.Field(alias="hasMore")]
    next_cursor: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="nextCursor"), pydantic.Field(alias="nextCursor")
    ] = None
    next_offset: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="nextOffset"), pydantic.Field(alias="nextOffset")
    ] = None
    runs: typing.List[ListBacktestJobsResponseRunsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
