# This file was auto-generated by Fern from our API Definition.

import typing

ListBacktestJobsResponseRunsItemStatus = typing.Union[
    typing.Literal["running", "done", "paused", "scheduled", "draft", "failed", "cancelled"], typing.Any
]
