# This file was auto-generated by Fern from our API Definition.

import typing

ListBacktestJobTrialsResponseTrialsItemStatus = typing.Union[
    typing.Literal["pending", "setup", "running", "verifying", "succeeded", "failed", "cancelled"], typing.Any
]
