# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .send_agent_chat_message_response_session_messages_item import SendAgentChatMessageResponseSessionMessagesItem


class SendAgentChatMessageResponseSession(UniversalBaseModel):
    """
    A live chat conversation with a registered agent version. Sessions are in-memory (lost on restart); the events, trace, and recorded run are durable.
    """

    agent_name: typing_extensions.Annotated[str, FieldMetadata(alias="agentName"), pydantic.Field(alias="agentName")]
    agent_version: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="agentVersion"),
        pydantic.Field(
            alias="agentVersion",
            description="Resolved registry version the session executes (`current`, else `stable`), pinned at session creation.",
        ),
    ]
    """
    Resolved registry version the session executes (`current`, else `stable`), pinned at session creation.
    """

    artifact_id: typing_extensions.Annotated[str, FieldMetadata(alias="artifactId"), pydantic.Field(alias="artifactId")]
    messages: typing.List[SendAgentChatMessageResponseSessionMessagesItem]
    run_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="runId"),
        pydantic.Field(
            alias="runId",
            description="Registry run id of the most recently recorded turn. Runs are immutable observations, so each turn records its own run; the shared `traceId` ties them into one conversation.",
        ),
    ]
    """
    Registry run id of the most recently recorded turn. Runs are immutable observations, so each turn records its own run; the shared `traceId` ties them into one conversation.
    """

    session_id: typing_extensions.Annotated[str, FieldMetadata(alias="sessionId"), pydantic.Field(alias="sessionId")]
    started_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="startedAt"), pydantic.Field(alias="startedAt")
    ]
    trace_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="traceId"),
        pydantic.Field(
            alias="traceId",
            description="Trace id shared by every event of the conversation. Opens in the timeline and `/v1/trace-tree/:trace_id`.",
        ),
    ]
    """
    Trace id shared by every event of the conversation. Opens in the timeline and `/v1/trace-tree/:trace_id`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
