# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .send_agent_chat_message_response_session_messages_item_role import (
    SendAgentChatMessageResponseSessionMessagesItemRole,
)
from .send_agent_chat_message_response_session_messages_item_steps_item import (
    SendAgentChatMessageResponseSessionMessagesItemStepsItem,
)


class SendAgentChatMessageResponseSessionMessagesItem(UniversalBaseModel):
    error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Present when the turn failed — the transcript keeps the user message and surfaces the failure instead of fabricating a reply.
    """

    event_ids: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="eventIds"),
        pydantic.Field(alias="eventIds", description="Canonical event ids this message ingested into the event store."),
    ] = None
    """
    Canonical event ids this message ingested into the event store.
    """

    message_id: typing_extensions.Annotated[str, FieldMetadata(alias="messageId"), pydantic.Field(alias="messageId")]
    occurred_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="occurredAt"), pydantic.Field(alias="occurredAt")
    ]
    role: SendAgentChatMessageResponseSessionMessagesItemRole
    steps: typing.Optional[typing.List[SendAgentChatMessageResponseSessionMessagesItemStepsItem]] = pydantic.Field(
        default=None
    )
    """
    Tool calls made while producing this message. Empty for user messages and failed turns.
    """

    text: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
