# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SourceSchema(UniversalBaseModel):
    """
    The inferred payload shape for one source and event type.
    """

    org_id: str
    source: str
    event_type: str
    version: int = pydantic.Field()
    """
    Bumped when the inferred shape changes.
    """

    field_names: typing.List[str]
    field_types: typing.List[str]
    sample_event: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
