# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SpanRequest(UniversalBaseModel):
    trace_id: str
    span_id: str
    parent_span_id: typing.Optional[str] = None
    event_id: typing.Optional[str] = None
    name: str
    kind: typing.Optional[str] = None
    status: typing.Optional[str] = None
    started_at: typing.Optional[dt.datetime] = None
    ended_at: typing.Optional[dt.datetime] = None
    duration_ms: typing.Optional[float] = None
    attributes: typing.Optional[typing.Any] = None
    links: typing.Optional[typing.Any] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
