# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .task_verifiers_item_weight import TaskVerifiersItemWeight


class TaskVerifiersItem(UniversalBaseModel):
    """
    One verifier bound to a task: a scorer from the tenant library plus the weight and pass threshold it carries for this task. Order is the position in the task's verifier list.
    """

    pass_threshold: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="passThreshold"), pydantic.Field(alias="passThreshold")
    ] = None
    scorer_id: typing_extensions.Annotated[str, FieldMetadata(alias="scorerId"), pydantic.Field(alias="scorerId")]
    weight: typing.Optional[TaskVerifiersItemWeight] = pydantic.Field(default=None)
    """
    Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
