# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .task_suite_snapshot_tasks_item_subject_kind import TaskSuiteSnapshotTasksItemSubjectKind
from .task_suite_snapshot_tasks_item_task import TaskSuiteSnapshotTasksItemTask
from .task_suite_snapshot_tasks_item_verifiers_item import TaskSuiteSnapshotTasksItemVerifiersItem


class TaskSuiteSnapshotTasksItem(UniversalBaseModel):
    """
    One task as frozen in a snapshot: the definition plus its verifiers with scorer content embedded. `trace_id` matches the `TraceSummary` in the same snapshot.
    """

    membership_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="membershipId"), pydantic.Field(alias="membershipId")
    ]
    subject_kind: typing_extensions.Annotated[
        TaskSuiteSnapshotTasksItemSubjectKind,
        FieldMetadata(alias="subjectKind"),
        pydantic.Field(
            alias="subjectKind",
            description="The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service.",
        ),
    ]
    """
    The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service.
    """

    task: TaskSuiteSnapshotTasksItemTask = pydantic.Field()
    """
    What a task asks for and how it is judged. Persisted on the membership (mutable working copy) and copied verbatim into every published version item. Verifier bindings live beside it (see `TaskVerifierBinding`).
    """

    trace_id: typing_extensions.Annotated[str, FieldMetadata(alias="traceId"), pydantic.Field(alias="traceId")]
    verifiers: typing.List[TaskSuiteSnapshotTasksItemVerifiersItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
