# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .task_split import TaskSplit
from .task_status import TaskStatus
from .task_subject_kind import TaskSubjectKind
from .task_task import TaskTask
from .task_verifiers_item import TaskVerifiersItem


class Task(UniversalBaseModel):
    """
    One task in a dataset: the trace summary (its seed, when it has one), the stable membership identity used for lazy event reads and explicit refreshes, and the task definition with its verifier bindings.
    """

    added_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="addedAt"), pydantic.Field(alias="addedAt")
    ] = None
    added_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="addedBy"), pydantic.Field(alias="addedBy")
    ] = None
    cluster_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="clusterId"), pydantic.Field(alias="clusterId")
    ] = None
    duration_ms: typing_extensions.Annotated[int, FieldMetadata(alias="durationMs"), pydantic.Field(alias="durationMs")]
    embedding: typing.Optional[typing.List[float]] = pydantic.Field(default=None)
    """
    Pre-computed 2D embedding in normalized `[-1, 1]` space.
    """

    event_count: typing_extensions.Annotated[int, FieldMetadata(alias="eventCount"), pydantic.Field(alias="eventCount")]
    label: str
    membership_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="membershipId"), pydantic.Field(alias="membershipId")
    ]
    note: typing.Optional[str] = None
    primary_source: typing_extensions.Annotated[
        str, FieldMetadata(alias="primarySource"), pydantic.Field(alias="primarySource")
    ]
    refresh_available: typing_extensions.Annotated[
        bool, FieldMetadata(alias="refreshAvailable"), pydantic.Field(alias="refreshAvailable")
    ]
    revision: int
    sources: typing.List[str]
    split: typing.Optional[TaskSplit] = pydantic.Field(default=None)
    """
    Train / validation / test split assignment.
    """

    started_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="startedAt"), pydantic.Field(alias="startedAt")
    ]
    status: TaskStatus = pydantic.Field()
    """
    Health status of a trace as judged by the dataset owner.
    """

    subject_id: typing_extensions.Annotated[str, FieldMetadata(alias="subjectId"), pydantic.Field(alias="subjectId")]
    subject_kind: typing_extensions.Annotated[
        TaskSubjectKind,
        FieldMetadata(alias="subjectKind"),
        pydantic.Field(
            alias="subjectKind",
            description="The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service.",
        ),
    ]
    """
    The canonical event-store subject curated into a Dataset. Providers that cannot form a real trace keep a single event subject rather than inventing a trace identifier. `Task` marks a hand-authored task with no captured subject; its revision holds zero events and its subject id is minted by the service.
    """

    task: typing.Optional[TaskTask] = pydantic.Field(default=None)
    """
    What a task asks for and how it is judged. Persisted on the membership (mutable working copy) and copied verbatim into every published version item. Verifier bindings live beside it (see `TaskVerifierBinding`).
    """

    trace_id: typing_extensions.Annotated[str, FieldMetadata(alias="traceId"), pydantic.Field(alias="traceId")]
    verifiers: typing.Optional[typing.List[TaskVerifiersItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
