# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TaskSuiteSnapshotEventsItem(UniversalBaseModel):
    """
    A single event rendered as a mark on the stream timeline. The full shape lives next to dataset shapes because `DatasetSnapshot.events` is the only consumer that ships over the wire today.
    """

    actor: typing.Optional[str] = None
    color: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional explicit color override; falls back to the source color.
    """

    correlation_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="correlationKey"),
        pydantic.Field(
            alias="correlationKey", description="Looser, app-defined grouping key (e.g. `conversation_id`)."
        ),
    ] = None
    """
    Looser, app-defined grouping key (e.g. `conversation_id`).
    """

    id: str
    message: typing.Optional[str] = None
    occurred_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="occurredAt"), pydantic.Field(alias="occurredAt", description="ISO timestamp.")
    ]
    """
    ISO timestamp.
    """

    parent_event_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="parentEventId"),
        pydantic.Field(alias="parentEventId", description="Direct causal predecessor."),
    ] = None
    """
    Direct causal predecessor.
    """

    payload: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Raw payload — shown JSON-pretty in the detail panel.
    """

    source: str = pydantic.Field()
    """
    Source/system the event came from (e.g. `intercom`, `stripe`).
    """

    stream: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional grouping (capture stream id) — currently informational.
    """

    trace_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="traceId"),
        pydantic.Field(alias="traceId", description="Trace this event belongs to."),
    ] = None
    """
    Trace this event belongs to.
    """

    trace_label: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="traceLabel"),
        pydantic.Field(alias="traceLabel", description="Human-friendly label for the trace."),
    ] = None
    """
    Human-friendly label for the trace.
    """

    type: str = pydantic.Field()
    """
    Event type within the source (e.g. `conversation.created`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
