# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .task_suite_detail_clusters_item import TaskSuiteDetailClustersItem
from .task_suite_detail_dataset import TaskSuiteDetailDataset
from .task_suite_detail_edges_item import TaskSuiteDetailEdgesItem


class TaskSuiteDetail(UniversalBaseModel):
    clusters: typing.List[TaskSuiteDetailClustersItem]
    dataset: TaskSuiteDetailDataset
    edges: typing.List[TaskSuiteDetailEdgesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
