# This file was auto-generated by Fern from our API Definition.

import typing

TaskSuiteSnapshotTasksItemVerifiersItemSource = typing.Union[
    typing.Literal["proposed", "library", "custom", "dataset"], typing.Any
]
