# This file was auto-generated by Fern from our API Definition.

import typing

TaskSuiteSnapshotTasksItemVerifiersItemKind = typing.Union[
    typing.Literal["rubric", "classifier", "metric", "embedding", "assertion", "code"], typing.Any
]
