# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .task_suite_snapshot_tasks_item_verifiers_item_code import TaskSuiteSnapshotTasksItemVerifiersItemCode
from .task_suite_snapshot_tasks_item_verifiers_item_judge import TaskSuiteSnapshotTasksItemVerifiersItemJudge
from .task_suite_snapshot_tasks_item_verifiers_item_kind import TaskSuiteSnapshotTasksItemVerifiersItemKind
from .task_suite_snapshot_tasks_item_verifiers_item_source import TaskSuiteSnapshotTasksItemVerifiersItemSource
from .task_suite_snapshot_tasks_item_verifiers_item_weight import TaskSuiteSnapshotTasksItemVerifiersItemWeight


class TaskSuiteSnapshotTasksItemVerifiersItem(UniversalBaseModel):
    code: typing.Optional[TaskSuiteSnapshotTasksItemVerifiersItemCode] = pydantic.Field(default=None)
    """
    Code handler snapshot — required when `kind` is `code`.
    """

    evidence: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional human-readable explanation of why this grader was proposed. For rubric graders this doubles as the judge prompt; library scorers inline their prompt here at launch so the recipe stays self-describing.
    """

    id: str
    judge: typing.Optional[TaskSuiteSnapshotTasksItemVerifiersItemJudge] = pydantic.Field(default=None)
    """
    LLM-judge configuration snapshot (rubric graders). `None` falls back to the default free-score judge behavior.
    """

    kind: TaskSuiteSnapshotTasksItemVerifiersItemKind
    label: str
    pass_threshold: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="passThreshold"),
        pydantic.Field(
            alias="passThreshold", description="Scores at or above this value render as passing in results."
        ),
    ] = None
    """
    Scores at or above this value render as passing in results.
    """

    scorer_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="scorerId"),
        pydantic.Field(
            alias="scorerId",
            description="Provenance: the library `Scorer.id` this grader was created from (when `source` is `library`). The prompt is snapshotted into `evidence` at launch, so editing the scorer later never mutates a past run.",
        ),
    ] = None
    """
    Provenance: the library `Scorer.id` this grader was created from (when `source` is `library`). The prompt is snapshotted into `evidence` at launch, so editing the scorer later never mutates a past run.
    """

    source: TaskSuiteSnapshotTasksItemVerifiersItemSource = pydantic.Field()
    """
    Grader source — where this grader came from when it was added to the recipe. Determines the chip copy ("proposed" vs "library" vs "custom" vs "dataset").
    """

    weight: TaskSuiteSnapshotTasksItemVerifiersItemWeight = pydantic.Field()
    """
    Grader weight bucket — `low | med | high` matches the segmented control in the GraderBuilder tray.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
