# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .task_suite_snapshot_clusters_item import TaskSuiteSnapshotClustersItem
from .task_suite_snapshot_dataset import TaskSuiteSnapshotDataset
from .task_suite_snapshot_edges_item import TaskSuiteSnapshotEdgesItem
from .task_suite_snapshot_events_item import TaskSuiteSnapshotEventsItem
from .task_suite_snapshot_tasks_item import TaskSuiteSnapshotTasksItem
from .task_suite_snapshot_traces_item import TaskSuiteSnapshotTracesItem


class TaskSuiteSnapshot(UniversalBaseModel):
    clusters: typing.List[TaskSuiteSnapshotClustersItem]
    dataset: TaskSuiteSnapshotDataset
    edges: typing.List[TaskSuiteSnapshotEdgesItem]
    events: typing.Optional[typing.List[TaskSuiteSnapshotEventsItem]] = pydantic.Field(default=None)
    """
    Optional pre-built event index used by the Timeline tab.
    """

    tasks: typing.Optional[typing.List[TaskSuiteSnapshotTasksItem]] = pydantic.Field(default=None)
    """
    Task definitions, one per trace. Absent on snapshots built by clients that only render the timeline.
    """

    traces: typing.List[TaskSuiteSnapshotTracesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
