# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .trial_event_job_finished_status import TrialEventJobFinishedStatus


class TrialEventJobFinished(UniversalBaseModel):
    """
    The job reached a terminal status. Carries a verdict so the list view can render without an extra fetch.
    """

    job_id: str
    status: TrialEventJobFinishedStatus = pydantic.Field()
    """
    Lifecycle state of an entire `BacktestJob`. Maps 1:1 onto the `status` column in `migrations/013_create_backtest_runtime.sql`.
    """

    verdict: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
