# This file was auto-generated by Fern from our API Definition.

import typing

TrialEventTrialPhaseChangedPhase = typing.Union[
    typing.Literal[
        "queued",
        "environment-start",
        "environment-ready",
        "agent-setup",
        "agent-running",
        "verifier-running",
        "artifact-collection",
        "cleanup",
        "done",
    ],
    typing.Any,
]
