# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .trial_event_trial_phase_changed_phase import TrialEventTrialPhaseChangedPhase


class TrialEventTrialPhaseChanged(UniversalBaseModel):
    """
    A trial transitioned phases (queued → running → verifying → done).
    """

    job_id: str
    phase: TrialEventTrialPhaseChangedPhase = pydantic.Field()
    """
    Phase of execution emitted on the SSE stream as the trial progresses. Distinct from `TrialStatus` — `TrialPhase` is fine-grained progress inside the lifecycle, `TrialStatus` is the persisted summary.
    """

    trial_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
