# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .trial_event_trial_finished_exception import TrialEventTrialFinishedException
from .trial_event_trial_finished_status import TrialEventTrialFinishedStatus


class TrialEventTrialFinished(UniversalBaseModel):
    """
    A trial reached a terminal status.
    """

    exception: typing.Optional[TrialEventTrialFinishedException] = pydantic.Field(default=None)
    """
    Captured exception info for a failed trial. Mirrors Harbor's `ExceptionInfo` — kind for routing/retry, message for humans.
    """

    job_id: str
    status: TrialEventTrialFinishedStatus = pydantic.Field()
    """
    Lifecycle state of a single `BacktestTrial` (one (case × agent) cell).
    """

    trial_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
