# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.event_page import EventPage
from .raw_client import AsyncRawTimelineClient, RawTimelineClient


class TimelineClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTimelineClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTimelineClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTimelineClient
        """
        return self._raw_client

    def get_timeline(
        self,
        entity_type: str,
        entity_id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        since: typing.Optional[str] = None,
        include_linked: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventPage:
        """
        Requires scope events:read or events:write. Cursor paginated, newest first.

        Pass `cursor` from `next_cursor` to read the following page, and stop when `has_more` is false. The cursor is opaque: it is a keyset over `(event_time, event_id)`, it is exclusive so a row cannot repeat across pages, and its encoding may change without notice. Do not parse or construct one.

        `include_linked=true` selects a different read that also returns causally linked events. That read is not paginated: it returns one page with `has_more` false, and it cannot be combined with `limit` or `cursor`. `since` is only available on that read, because the paginated read has no time filter.

        Parameters
        ----------
        entity_type : str

        entity_id : str

        limit : typing.Optional[int]
            Page size. Values above the maximum are reduced to it, not rejected.

        cursor : typing.Optional[str]
            Opaque cursor from a previous response's next_cursor

        since : typing.Optional[str]
            Relative time window, for example last_7d.

        include_linked : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventPage
            A page of timeline events

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.timeline.get_timeline(
            entity_type="entity_type",
            entity_id="entity_id",
        )
        """
        _response = self._raw_client.get_timeline(
            entity_type,
            entity_id,
            limit=limit,
            cursor=cursor,
            since=since,
            include_linked=include_linked,
            request_options=request_options,
        )
        return _response.data


class AsyncTimelineClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTimelineClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTimelineClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTimelineClient
        """
        return self._raw_client

    async def get_timeline(
        self,
        entity_type: str,
        entity_id: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        since: typing.Optional[str] = None,
        include_linked: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventPage:
        """
        Requires scope events:read or events:write. Cursor paginated, newest first.

        Pass `cursor` from `next_cursor` to read the following page, and stop when `has_more` is false. The cursor is opaque: it is a keyset over `(event_time, event_id)`, it is exclusive so a row cannot repeat across pages, and its encoding may change without notice. Do not parse or construct one.

        `include_linked=true` selects a different read that also returns causally linked events. That read is not paginated: it returns one page with `has_more` false, and it cannot be combined with `limit` or `cursor`. `since` is only available on that read, because the paginated read has no time filter.

        Parameters
        ----------
        entity_type : str

        entity_id : str

        limit : typing.Optional[int]
            Page size. Values above the maximum are reduced to it, not rejected.

        cursor : typing.Optional[str]
            Opaque cursor from a previous response's next_cursor

        since : typing.Optional[str]
            Relative time window, for example last_7d.

        include_linked : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventPage
            A page of timeline events

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.timeline.get_timeline(
                entity_type="entity_type",
                entity_id="entity_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_timeline(
            entity_type,
            entity_id,
            limit=limit,
            cursor=cursor,
            since=since,
            include_linked=include_linked,
            request_options=request_options,
        )
        return _response.data
