# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.event_list_response import EventListResponse
from ..types.event_result import EventResult
from ..types.ingest_request import IngestRequest
from ..types.ingest_response import IngestResponse
from .raw_client import AsyncRawEventsClient, RawEventsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EventsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawEventsClient
        """
        return self._raw_client

    def query_events(
        self,
        *,
        source: typing.Optional[str] = None,
        topic: typing.Optional[str] = None,
        event_type: typing.Optional[str] = None,
        entity_type: typing.Optional[str] = None,
        entity_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        since: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventListResponse:
        """
        Requires scope events:read or events:write. Results are scoped to the tenant of the API key and ordered newest first by event time and event ID. Pass the opaque `next_cursor` as `cursor` to continue without an offset scan.

        Parameters
        ----------
        source : typing.Optional[str]

        topic : typing.Optional[str]

        event_type : typing.Optional[str]

        entity_type : typing.Optional[str]

        entity_id : typing.Optional[str]

        limit : typing.Optional[int]
            Page size. Values above 200 are clamped to 200.

        cursor : typing.Optional[str]
            Opaque position returned as `next_cursor` by the preceding page.

        since : typing.Optional[str]
            Relative time window, for example last_7d.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventListResponse
            Matching events

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.events.query_events()
        """
        _response = self._raw_client.query_events(
            source=source,
            topic=topic,
            event_type=event_type,
            entity_type=entity_type,
            entity_id=entity_id,
            limit=limit,
            cursor=cursor,
            since=since,
            request_options=request_options,
        )
        return _response.data

    def ingest_event(
        self,
        *,
        source: str,
        topic: str,
        event_type: str,
        entities: typing.Optional[typing.Dict[str, str]] = OMIT,
        payload: typing.Optional[typing.Any] = OMIT,
        timestamp: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestResponse:
        """
        Requires scope events:write.

        Parameters
        ----------
        source : str

        topic : str

        event_type : str

        entities : typing.Optional[typing.Dict[str, str]]

        payload : typing.Optional[typing.Any]

        timestamp : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestResponse
            Event stored

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.events.ingest_event(
            source="my-agent",
            topic="conversations",
            event_type="message.sent",
        )
        """
        _response = self._raw_client.ingest_event(
            source=source,
            topic=topic,
            event_type=event_type,
            entities=entities,
            payload=payload,
            timestamp=timestamp,
            request_options=request_options,
        )
        return _response.data

    def ingest_event_batch(
        self, *, request: typing.Sequence[IngestRequest], request_options: typing.Optional[RequestOptions] = None
    ) -> IngestResponse:
        """
        Requires scope events:write. Maximum 1000 events per batch; larger batches are rejected with 422. Request bodies over the size limit are rejected with 413. Each request consumes 10 rate-limit units.

        Parameters
        ----------
        request : typing.Sequence[IngestRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestResponse
            Events stored

        Examples
        --------
        from chroniclelabs import Chronicle, IngestRequest

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        client.events.ingest_event_batch(
            request=[
                IngestRequest(
                    source="my-agent",
                    topic="conversations",
                    event_type="message.sent",
                )
            ],
        )
        """
        _response = self._raw_client.ingest_event_batch(request=request, request_options=request_options)
        return _response.data

    def stream_events(
        self,
        *,
        source: typing.Optional[str] = None,
        event_type: typing.Optional[str] = None,
        entity_type: typing.Optional[str] = None,
        entity_id: typing.Optional[str] = None,
        last_event_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Iterator[EventResult]:
        """
        Requires scope events:read or events:write. A Server-Sent Events stream of events matching the optional filters, held open indefinitely.

        Opening a stream consumes 5 rate-limit units.

        Each message has `event: event` and a `data` field carrying one EventResult as JSON. A comment line arrives every 15 seconds so intermediaries do not close an idle connection.

        Every message carries an opaque, stream-specific `id` backed by a monotonic per-tenant delivery sequence. It records ingestion order, independently of the source event's `event_time`. Record the last id you processed and do not parse or construct it.

        When `Last-Event-ID` is present, the server first establishes the live subscription, replays matching stored events strictly after that position in ascending order, and then continues with live delivery. Events committed at the history-to-live boundary may be delivered more than once, so consumers should deduplicate by `event_id`. This provides at-least-once delivery across a reconnect without leaving a gap.

        Replay is limited to 1000 matching events. An older position returns 409 before the stream opens. Slow consumers are disconnected when the bounded live buffer fills and should reconnect with their last processed id. Concurrent streams are limited per tenant and may return 429 with `Retry-After`.

        Parameters
        ----------
        source : typing.Optional[str]

        event_type : typing.Optional[str]

        entity_type : typing.Optional[str]

        entity_id : typing.Optional[str]

        last_event_id : typing.Optional[str]
            Opaque id from the last SSE message the client processed.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.Iterator[EventResult]
            SSE stream

        Examples
        --------
        from chroniclelabs import Chronicle

        client = Chronicle(
            token="YOUR_TOKEN",
        )
        response = client.events.stream_events()
        for chunk in response:
            yield chunk
        """
        with self._raw_client.stream_events(
            source=source,
            event_type=event_type,
            entity_type=entity_type,
            entity_id=entity_id,
            last_event_id=last_event_id,
            request_options=request_options,
        ) as r:
            yield from r.data


class AsyncEventsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawEventsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawEventsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawEventsClient
        """
        return self._raw_client

    async def query_events(
        self,
        *,
        source: typing.Optional[str] = None,
        topic: typing.Optional[str] = None,
        event_type: typing.Optional[str] = None,
        entity_type: typing.Optional[str] = None,
        entity_id: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        since: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> EventListResponse:
        """
        Requires scope events:read or events:write. Results are scoped to the tenant of the API key and ordered newest first by event time and event ID. Pass the opaque `next_cursor` as `cursor` to continue without an offset scan.

        Parameters
        ----------
        source : typing.Optional[str]

        topic : typing.Optional[str]

        event_type : typing.Optional[str]

        entity_type : typing.Optional[str]

        entity_id : typing.Optional[str]

        limit : typing.Optional[int]
            Page size. Values above 200 are clamped to 200.

        cursor : typing.Optional[str]
            Opaque position returned as `next_cursor` by the preceding page.

        since : typing.Optional[str]
            Relative time window, for example last_7d.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EventListResponse
            Matching events

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.events.query_events()


        asyncio.run(main())
        """
        _response = await self._raw_client.query_events(
            source=source,
            topic=topic,
            event_type=event_type,
            entity_type=entity_type,
            entity_id=entity_id,
            limit=limit,
            cursor=cursor,
            since=since,
            request_options=request_options,
        )
        return _response.data

    async def ingest_event(
        self,
        *,
        source: str,
        topic: str,
        event_type: str,
        entities: typing.Optional[typing.Dict[str, str]] = OMIT,
        payload: typing.Optional[typing.Any] = OMIT,
        timestamp: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> IngestResponse:
        """
        Requires scope events:write.

        Parameters
        ----------
        source : str

        topic : str

        event_type : str

        entities : typing.Optional[typing.Dict[str, str]]

        payload : typing.Optional[typing.Any]

        timestamp : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestResponse
            Event stored

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.events.ingest_event(
                source="my-agent",
                topic="conversations",
                event_type="message.sent",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.ingest_event(
            source=source,
            topic=topic,
            event_type=event_type,
            entities=entities,
            payload=payload,
            timestamp=timestamp,
            request_options=request_options,
        )
        return _response.data

    async def ingest_event_batch(
        self, *, request: typing.Sequence[IngestRequest], request_options: typing.Optional[RequestOptions] = None
    ) -> IngestResponse:
        """
        Requires scope events:write. Maximum 1000 events per batch; larger batches are rejected with 422. Request bodies over the size limit are rejected with 413. Each request consumes 10 rate-limit units.

        Parameters
        ----------
        request : typing.Sequence[IngestRequest]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        IngestResponse
            Events stored

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle, IngestRequest

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.events.ingest_event_batch(
                request=[
                    IngestRequest(
                        source="my-agent",
                        topic="conversations",
                        event_type="message.sent",
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.ingest_event_batch(request=request, request_options=request_options)
        return _response.data

    async def stream_events(
        self,
        *,
        source: typing.Optional[str] = None,
        event_type: typing.Optional[str] = None,
        entity_type: typing.Optional[str] = None,
        entity_id: typing.Optional[str] = None,
        last_event_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.AsyncIterator[EventResult]:
        """
        Requires scope events:read or events:write. A Server-Sent Events stream of events matching the optional filters, held open indefinitely.

        Opening a stream consumes 5 rate-limit units.

        Each message has `event: event` and a `data` field carrying one EventResult as JSON. A comment line arrives every 15 seconds so intermediaries do not close an idle connection.

        Every message carries an opaque, stream-specific `id` backed by a monotonic per-tenant delivery sequence. It records ingestion order, independently of the source event's `event_time`. Record the last id you processed and do not parse or construct it.

        When `Last-Event-ID` is present, the server first establishes the live subscription, replays matching stored events strictly after that position in ascending order, and then continues with live delivery. Events committed at the history-to-live boundary may be delivered more than once, so consumers should deduplicate by `event_id`. This provides at-least-once delivery across a reconnect without leaving a gap.

        Replay is limited to 1000 matching events. An older position returns 409 before the stream opens. Slow consumers are disconnected when the bounded live buffer fills and should reconnect with their last processed id. Concurrent streams are limited per tenant and may return 429 with `Retry-After`.

        Parameters
        ----------
        source : typing.Optional[str]

        event_type : typing.Optional[str]

        entity_type : typing.Optional[str]

        entity_id : typing.Optional[str]

        last_event_id : typing.Optional[str]
            Opaque id from the last SSE message the client processed.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Yields
        ------
        typing.AsyncIterator[EventResult]
            SSE stream

        Examples
        --------
        import asyncio

        from chroniclelabs import AsyncChronicle

        client = AsyncChronicle(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            response = client.events.stream_events()
            async for chunk in response:
                yield chunk


        asyncio.run(main())
        """
        async with self._raw_client.stream_events(
            source=source,
            event_type=event_type,
            entity_type=entity_type,
            entity_id=entity_id,
            last_event_id=last_event_id,
            request_options=request_options,
        ) as r:
            async for _chunk in r.data:
                yield _chunk
