# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .record_agent_runs_request_runs_item import RecordAgentRunsRequestRunsItem
    from .record_agent_runs_request_runs_item_error import RecordAgentRunsRequestRunsItemError
    from .record_agent_runs_request_runs_item_operation import RecordAgentRunsRequestRunsItemOperation
    from .record_agent_runs_request_runs_item_prepared_call import RecordAgentRunsRequestRunsItemPreparedCall
    from .record_agent_runs_request_runs_item_response import RecordAgentRunsRequestRunsItemResponse
    from .record_agent_runs_request_runs_item_response_usage import RecordAgentRunsRequestRunsItemResponseUsage
    from .record_agent_runs_request_runs_item_status import RecordAgentRunsRequestRunsItemStatus
    from .record_agent_runs_request_runs_item_tool_calls_item import RecordAgentRunsRequestRunsItemToolCallsItem
    from .record_agent_runs_request_runs_item_tool_calls_item_error import (
        RecordAgentRunsRequestRunsItemToolCallsItemError,
    )
    from .record_agent_runs_request_runs_item_tool_calls_item_status import (
        RecordAgentRunsRequestRunsItemToolCallsItemStatus,
    )
    from .record_agent_runs_response import RecordAgentRunsResponse
    from .register_agent_artifact_request_artifact import RegisterAgentArtifactRequestArtifact
    from .register_agent_artifact_request_artifact_framework import RegisterAgentArtifactRequestArtifactFramework
    from .register_agent_artifact_request_artifact_input_contract_preview import (
        RegisterAgentArtifactRequestArtifactInputContractPreview,
    )
    from .register_agent_artifact_request_artifact_knowledge_sources_item import (
        RegisterAgentArtifactRequestArtifactKnowledgeSourcesItem,
    )
    from .register_agent_artifact_request_artifact_knowledge_sources_item_kind import (
        RegisterAgentArtifactRequestArtifactKnowledgeSourcesItemKind,
    )
    from .register_agent_artifact_request_artifact_model import RegisterAgentArtifactRequestArtifactModel
    from .register_agent_artifact_request_artifact_output_contract_preview import (
        RegisterAgentArtifactRequestArtifactOutputContractPreview,
    )
    from .register_agent_artifact_request_artifact_policy import RegisterAgentArtifactRequestArtifactPolicy
    from .register_agent_artifact_request_artifact_provenance import RegisterAgentArtifactRequestArtifactProvenance
    from .register_agent_artifact_request_artifact_tools_item import RegisterAgentArtifactRequestArtifactToolsItem
    from .register_agent_artifact_request_artifact_workflow_graph_preview import (
        RegisterAgentArtifactRequestArtifactWorkflowGraphPreview,
    )
    from .register_agent_artifact_request_artifact_workflow_graph_preview_edges_item import (
        RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewEdgesItem,
    )
    from .register_agent_artifact_request_artifact_workflow_graph_preview_nodes_item import (
        RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewNodesItem,
    )
    from .register_agent_artifact_request_artifact_workflow_graph_preview_nodes_item_kind import (
        RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewNodesItemKind,
    )
    from .register_agent_artifact_request_metadata import RegisterAgentArtifactRequestMetadata
    from .register_agent_artifact_request_status import RegisterAgentArtifactRequestStatus
_dynamic_imports: typing.Dict[str, str] = {
    "RecordAgentRunsRequestRunsItem": ".record_agent_runs_request_runs_item",
    "RecordAgentRunsRequestRunsItemError": ".record_agent_runs_request_runs_item_error",
    "RecordAgentRunsRequestRunsItemOperation": ".record_agent_runs_request_runs_item_operation",
    "RecordAgentRunsRequestRunsItemPreparedCall": ".record_agent_runs_request_runs_item_prepared_call",
    "RecordAgentRunsRequestRunsItemResponse": ".record_agent_runs_request_runs_item_response",
    "RecordAgentRunsRequestRunsItemResponseUsage": ".record_agent_runs_request_runs_item_response_usage",
    "RecordAgentRunsRequestRunsItemStatus": ".record_agent_runs_request_runs_item_status",
    "RecordAgentRunsRequestRunsItemToolCallsItem": ".record_agent_runs_request_runs_item_tool_calls_item",
    "RecordAgentRunsRequestRunsItemToolCallsItemError": ".record_agent_runs_request_runs_item_tool_calls_item_error",
    "RecordAgentRunsRequestRunsItemToolCallsItemStatus": ".record_agent_runs_request_runs_item_tool_calls_item_status",
    "RecordAgentRunsResponse": ".record_agent_runs_response",
    "RegisterAgentArtifactRequestArtifact": ".register_agent_artifact_request_artifact",
    "RegisterAgentArtifactRequestArtifactFramework": ".register_agent_artifact_request_artifact_framework",
    "RegisterAgentArtifactRequestArtifactInputContractPreview": ".register_agent_artifact_request_artifact_input_contract_preview",
    "RegisterAgentArtifactRequestArtifactKnowledgeSourcesItem": ".register_agent_artifact_request_artifact_knowledge_sources_item",
    "RegisterAgentArtifactRequestArtifactKnowledgeSourcesItemKind": ".register_agent_artifact_request_artifact_knowledge_sources_item_kind",
    "RegisterAgentArtifactRequestArtifactModel": ".register_agent_artifact_request_artifact_model",
    "RegisterAgentArtifactRequestArtifactOutputContractPreview": ".register_agent_artifact_request_artifact_output_contract_preview",
    "RegisterAgentArtifactRequestArtifactPolicy": ".register_agent_artifact_request_artifact_policy",
    "RegisterAgentArtifactRequestArtifactProvenance": ".register_agent_artifact_request_artifact_provenance",
    "RegisterAgentArtifactRequestArtifactToolsItem": ".register_agent_artifact_request_artifact_tools_item",
    "RegisterAgentArtifactRequestArtifactWorkflowGraphPreview": ".register_agent_artifact_request_artifact_workflow_graph_preview",
    "RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewEdgesItem": ".register_agent_artifact_request_artifact_workflow_graph_preview_edges_item",
    "RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewNodesItem": ".register_agent_artifact_request_artifact_workflow_graph_preview_nodes_item",
    "RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewNodesItemKind": ".register_agent_artifact_request_artifact_workflow_graph_preview_nodes_item_kind",
    "RegisterAgentArtifactRequestMetadata": ".register_agent_artifact_request_metadata",
    "RegisterAgentArtifactRequestStatus": ".register_agent_artifact_request_status",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "RecordAgentRunsRequestRunsItem",
    "RecordAgentRunsRequestRunsItemError",
    "RecordAgentRunsRequestRunsItemOperation",
    "RecordAgentRunsRequestRunsItemPreparedCall",
    "RecordAgentRunsRequestRunsItemResponse",
    "RecordAgentRunsRequestRunsItemResponseUsage",
    "RecordAgentRunsRequestRunsItemStatus",
    "RecordAgentRunsRequestRunsItemToolCallsItem",
    "RecordAgentRunsRequestRunsItemToolCallsItemError",
    "RecordAgentRunsRequestRunsItemToolCallsItemStatus",
    "RecordAgentRunsResponse",
    "RegisterAgentArtifactRequestArtifact",
    "RegisterAgentArtifactRequestArtifactFramework",
    "RegisterAgentArtifactRequestArtifactInputContractPreview",
    "RegisterAgentArtifactRequestArtifactKnowledgeSourcesItem",
    "RegisterAgentArtifactRequestArtifactKnowledgeSourcesItemKind",
    "RegisterAgentArtifactRequestArtifactModel",
    "RegisterAgentArtifactRequestArtifactOutputContractPreview",
    "RegisterAgentArtifactRequestArtifactPolicy",
    "RegisterAgentArtifactRequestArtifactProvenance",
    "RegisterAgentArtifactRequestArtifactToolsItem",
    "RegisterAgentArtifactRequestArtifactWorkflowGraphPreview",
    "RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewEdgesItem",
    "RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewNodesItem",
    "RegisterAgentArtifactRequestArtifactWorkflowGraphPreviewNodesItemKind",
    "RegisterAgentArtifactRequestMetadata",
    "RegisterAgentArtifactRequestStatus",
]
