# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .record_agent_runs_request_runs_item_tool_calls_item_error import RecordAgentRunsRequestRunsItemToolCallsItemError
from .record_agent_runs_request_runs_item_tool_calls_item_status import (
    RecordAgentRunsRequestRunsItemToolCallsItemStatus,
)


class RecordAgentRunsRequestRunsItemToolCallsItem(UniversalBaseModel):
    args_hash: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="argsHash"), pydantic.Field(alias="argsHash")
    ] = None
    args_preview: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="argsPreview"),
        pydantic.Field(alias="argsPreview", description="Optional small preview of the tool args."),
    ] = None
    """
    Optional small preview of the tool args.
    """

    call_id: typing_extensions.Annotated[str, FieldMetadata(alias="callId"), pydantic.Field(alias="callId")]
    duration_ms: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="durationMs"), pydantic.Field(alias="durationMs")
    ] = None
    error: typing.Optional[RecordAgentRunsRequestRunsItemToolCallsItemError] = None
    finished_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="finishedAt"), pydantic.Field(alias="finishedAt")
    ] = None
    result_hash: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="resultHash"), pydantic.Field(alias="resultHash")
    ] = None
    result_preview: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="resultPreview"),
        pydantic.Field(alias="resultPreview"),
    ] = None
    started_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="startedAt"), pydantic.Field(alias="startedAt")
    ]
    status: RecordAgentRunsRequestRunsItemToolCallsItemStatus
    tool_name: typing_extensions.Annotated[str, FieldMetadata(alias="toolName"), pydantic.Field(alias="toolName")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
