# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .record_agent_runs_request_runs_item_response_usage import RecordAgentRunsRequestRunsItemResponseUsage


class RecordAgentRunsRequestRunsItemResponse(UniversalBaseModel):
    body_hash: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="bodyHash"), pydantic.Field(alias="bodyHash")
    ] = None
    finish_reason: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="finishReason"), pydantic.Field(alias="finishReason")
    ] = None
    headers: typing.Optional[typing.Dict[str, typing.Optional[str]]] = pydantic.Field(default=None)
    """
    Subset of headers preserved for the run drawer.
    """

    id: typing.Optional[str] = None
    model_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="modelId"), pydantic.Field(alias="modelId")
    ] = None
    model_metadata: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="modelMetadata"),
        pydantic.Field(alias="modelMetadata"),
    ] = None
    provider_metadata: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="providerMetadata"),
        pydantic.Field(alias="providerMetadata"),
    ] = None
    usage: typing.Optional[RecordAgentRunsRequestRunsItemResponseUsage] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
