# This file was auto-generated by Fern from our API Definition.

import typing

RecordAgentRunsRequestRunsItemToolCallsItemStatus = typing.Union[
    typing.Literal["started", "success", "error"], typing.Any
]
