# This file was auto-generated by Fern from our API Definition.

import typing

RegisterAgentArtifactRequestStatus = typing.Union[
    typing.Literal["current", "stable", "deprecated", "draft"], typing.Any
]
