# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class RegisterAgentArtifactRequestMetadata(UniversalBaseModel):
    """
    Mutable, human-authored metadata attached to a logical Agent identity. Artifact configuration remains immutable inside `AgentRegistryVersionRecord`.
    """

    capability_tags: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="capabilityTags"), pydantic.Field(alias="capabilityTags")
    ] = None
    category: typing.Optional[str] = None
    environment: typing.Optional[str] = None
    owner: typing.Optional[str] = None
    persona_summary: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="personaSummary"), pydantic.Field(alias="personaSummary")
    ] = None
    playground_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="playgroundUrl"), pydantic.Field(alias="playgroundUrl")
    ] = None
    purpose: typing.Optional[str] = None
    runbook_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="runbookUrl"), pydantic.Field(alias="runbookUrl")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
