# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class RegisterAgentArtifactRequestArtifactProvenance(UniversalBaseModel):
    ai_sdk_version: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="aiSdkVersion"), pydantic.Field(alias="aiSdkVersion")
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    dependency_lock_hash: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="dependencyLockHash"), pydantic.Field(alias="dependencyLockHash")
    ] = None
    framework_version: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="frameworkVersion"), pydantic.Field(alias="frameworkVersion")
    ] = None
    git_sha: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="gitSha"), pydantic.Field(alias="gitSha")
    ] = None
    published_by: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="publishedBy"), pydantic.Field(alias="publishedBy")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
