# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .register_agent_artifact_request_artifact_framework import RegisterAgentArtifactRequestArtifactFramework
from .register_agent_artifact_request_artifact_input_contract_preview import (
    RegisterAgentArtifactRequestArtifactInputContractPreview,
)
from .register_agent_artifact_request_artifact_knowledge_sources_item import (
    RegisterAgentArtifactRequestArtifactKnowledgeSourcesItem,
)
from .register_agent_artifact_request_artifact_model import RegisterAgentArtifactRequestArtifactModel
from .register_agent_artifact_request_artifact_output_contract_preview import (
    RegisterAgentArtifactRequestArtifactOutputContractPreview,
)
from .register_agent_artifact_request_artifact_policy import RegisterAgentArtifactRequestArtifactPolicy
from .register_agent_artifact_request_artifact_provenance import RegisterAgentArtifactRequestArtifactProvenance
from .register_agent_artifact_request_artifact_tools_item import RegisterAgentArtifactRequestArtifactToolsItem
from .register_agent_artifact_request_artifact_workflow_graph_preview import (
    RegisterAgentArtifactRequestArtifactWorkflowGraphPreview,
)


class RegisterAgentArtifactRequestArtifact(UniversalBaseModel):
    artifact_id: typing_extensions.Annotated[str, FieldMetadata(alias="artifactId"), pydantic.Field(alias="artifactId")]
    config_hash: typing_extensions.Annotated[str, FieldMetadata(alias="configHash"), pydantic.Field(alias="configHash")]
    description: typing.Optional[str] = None
    framework: RegisterAgentArtifactRequestArtifactFramework = pydantic.Field()
    """
    Framework label. Multi-word kebab-case to match the existing TS union (`vercel-ai-sdk`, `openai-agents-python`, etc.).
    """

    input_contract_preview: typing_extensions.Annotated[
        typing.Optional[RegisterAgentArtifactRequestArtifactInputContractPreview],
        FieldMetadata(alias="inputContractPreview"),
        pydantic.Field(
            alias="inputContractPreview", description="Compact preview of the input contract this artifact expects."
        ),
    ] = None
    """
    Compact preview of the input contract this artifact expects.
    """

    instructions: typing.Optional[str] = None
    instructions_hash: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="instructionsHash"), pydantic.Field(alias="instructionsHash")
    ] = None
    knowledge_sources: typing_extensions.Annotated[
        typing.Optional[typing.List[RegisterAgentArtifactRequestArtifactKnowledgeSourcesItem]],
        FieldMetadata(alias="knowledgeSources"),
        pydantic.Field(alias="knowledgeSources"),
    ] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    model: RegisterAgentArtifactRequestArtifactModel
    name: str
    output_contract_preview: typing_extensions.Annotated[
        typing.Optional[RegisterAgentArtifactRequestArtifactOutputContractPreview],
        FieldMetadata(alias="outputContractPreview"),
        pydantic.Field(
            alias="outputContractPreview", description="Compact preview of the output contract this artifact emits."
        ),
    ] = None
    """
    Compact preview of the output contract this artifact emits.
    """

    policy: typing.Optional[RegisterAgentArtifactRequestArtifactPolicy] = None
    provenance: RegisterAgentArtifactRequestArtifactProvenance
    provider_options: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="providerOptions"),
        pydantic.Field(alias="providerOptions"),
    ] = None
    provider_options_hash: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="providerOptionsHash"), pydantic.Field(alias="providerOptionsHash")
    ] = None
    schema_version: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="schemaVersion"),
        pydantic.Field(
            alias="schemaVersion",
            description='Schema marker — frontend code matches against the literal string `"agent-artifact-v1"` so newer payloads can co-exist when we evolve the shape.',
        ),
    ]
    """
    Schema marker — frontend code matches against the literal string `"agent-artifact-v1"` so newer payloads can co-exist when we evolve the shape.
    """

    tools: typing.List[RegisterAgentArtifactRequestArtifactToolsItem]
    version: str
    workflow_graph_preview: typing_extensions.Annotated[
        typing.Optional[RegisterAgentArtifactRequestArtifactWorkflowGraphPreview],
        FieldMetadata(alias="workflowGraphPreview"),
        pydantic.Field(alias="workflowGraphPreview"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
