# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .register_agent_artifact_request_artifact_knowledge_sources_item_kind import (
    RegisterAgentArtifactRequestArtifactKnowledgeSourcesItemKind,
)


class RegisterAgentArtifactRequestArtifactKnowledgeSourcesItem(UniversalBaseModel):
    href: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional jump-out link.
    """

    id: str
    kind: RegisterAgentArtifactRequestArtifactKnowledgeSourcesItemKind
    label: str
    size_label: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sizeLabel"),
        pydantic.Field(alias="sizeLabel", description='Optional human-readable size hint, e.g. "12.4k docs".'),
    ] = None
    """
    Optional human-readable size hint, e.g. "12.4k docs".
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
